<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Semana 4. Boxplot, cuantiles y variables categóricas – Clases Pascual Bravo 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-63bd06c2c145d35a53f198c60a9c2611.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Unidad 1. Análisis descriptivo y exploratorio</a></li><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-04/index.html">Semana 4. Boxplot, cuantiles y variables categóricas</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Clases Pascual Bravo 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del módulo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Análisis descriptivo y exploratorio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 1. Presentación y entorno de trabajo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 2. Tipos de variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 3. Localización, dispersión y tablas de frecuencia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-04/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Semana 4. Boxplot, cuantiles y variables categóricas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-05/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 5. Dispersión, condicionales y cierre de la Unidad 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/laboratorio-pandas-eda/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Laboratorio: análisis exploratorio con pandas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelos de probabilidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación de la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/unidad-02/variables-aleatorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Variables aleatorias y espacio muestral</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/unidad-02/presentacion-variables-aleatorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Presentación: variables aleatorias</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#de-qué-va-esta-semana" id="toc-de-qué-va-esta-semana" class="nav-link active" data-scroll-target="#de-qué-va-esta-semana"><span class="header-section-number">1</span> De qué va esta semana</a></li>
  <li><a href="#recapitulación-breve" id="toc-recapitulación-breve" class="nav-link" data-scroll-target="#recapitulación-breve"><span class="header-section-number">2</span> Recapitulación breve</a></li>
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles"><span class="header-section-number">3</span> Percentiles</a></li>
  <li><a href="#el-diagrama-de-caja-boxplot" id="toc-el-diagrama-de-caja-boxplot" class="nav-link" data-scroll-target="#el-diagrama-de-caja-boxplot"><span class="header-section-number">4</span> El diagrama de caja (boxplot)</a></li>
  <li><a href="#variables-categóricas-moda-y-gráficos-de-barras" id="toc-variables-categóricas-moda-y-gráficos-de-barras" class="nav-link" data-scroll-target="#variables-categóricas-moda-y-gráficos-de-barras"><span class="header-section-number">5</span> Variables categóricas: moda y gráficos de barras</a></li>
  <li><a href="#tablas-de-contingencia" id="toc-tablas-de-contingencia" class="nav-link" data-scroll-target="#tablas-de-contingencia"><span class="header-section-number">6</span> Tablas de contingencia</a></li>
  <li><a href="#caso-integrador-retrasos-por-aerolínea" id="toc-caso-integrador-retrasos-por-aerolínea" class="nav-link" data-scroll-target="#caso-integrador-retrasos-por-aerolínea"><span class="header-section-number">7</span> Caso integrador: retrasos por aerolínea</a></li>
  <li><a href="#ejercicio-final-constrúyelo-tú-de-principio-a-fin" id="toc-ejercicio-final-constrúyelo-tú-de-principio-a-fin" class="nav-link" data-scroll-target="#ejercicio-final-constrúyelo-tú-de-principio-a-fin"><span class="header-section-number">8</span> Ejercicio final: constrúyelo tú, de principio a fin</a>
  <ul class="collapse">
  <li><a href="#paso-1.-consigue-un-dataset-con-al-menos-una-variable-numérica-y-una-categórica" id="toc-paso-1.-consigue-un-dataset-con-al-menos-una-variable-numérica-y-una-categórica" class="nav-link" data-scroll-target="#paso-1.-consigue-un-dataset-con-al-menos-una-variable-numérica-y-una-categórica">Paso 1. Consigue un dataset con al menos una variable numérica y una categórica</a></li>
  <li><a href="#paso-2.-formula-tus-propias-preguntas" id="toc-paso-2.-formula-tus-propias-preguntas" class="nav-link" data-scroll-target="#paso-2.-formula-tus-propias-preguntas">Paso 2. Formula tus propias preguntas</a></li>
  <li><a href="#paso-3.-responde-y-justifica-cada-una" id="toc-paso-3.-responde-y-justifica-cada-una" class="nav-link" data-scroll-target="#paso-3.-responde-y-justifica-cada-una">Paso 3. Responde y justifica cada una</a></li>
  <li><a href="#paso-4.-si-tienes-una-variable-numérica-y-una-categórica-juntas-crúzalas" id="toc-paso-4.-si-tienes-una-variable-numérica-y-una-categórica-juntas-crúzalas" class="nav-link" data-scroll-target="#paso-4.-si-tienes-una-variable-numérica-y-una-categórica-juntas-crúzalas">Paso 4. Si tienes una variable numérica y una categórica juntas, crúzalas</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">9</span> Errores frecuentes</a></li>
  <li><a href="#lista-de-chequeo-de-la-semana" id="toc-lista-de-chequeo-de-la-semana" class="nav-link" data-scroll-target="#lista-de-chequeo-de-la-semana"><span class="header-section-number">10</span> Lista de chequeo de la semana</a></li>
  <li><a href="#lo-que-viene" id="toc-lo-que-viene" class="nav-link" data-scroll-target="#lo-que-viene"><span class="header-section-number">11</span> Lo que viene</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">12</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Unidad 1. Análisis descriptivo y exploratorio</a></li><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-04/index.html">Semana 4. Boxplot, cuantiles y variables categóricas</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Semana 4. Boxplot, cuantiles y variables categóricas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">26 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<tbody>
<tr class="odd">
<td>Módulo</td>
<td>Estadística para Analítica</td>
</tr>
<tr class="even">
<td>Programa</td>
<td>Especialización en Big Data</td>
</tr>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Análisis descriptivo y exploratorio de datos</td>
</tr>
</tbody>
</table>
</div>
<p><a href="presentacion-boxplot-categoricas.html" class="btn btn-primary" role="button">Abrir la presentación de la sesión</a></p>
<section id="de-qué-va-esta-semana" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="de-qué-va-esta-semana"><span class="header-section-number">1</span> De qué va esta semana</h2>
<p>Seguimos con el capítulo 1 de <em>Estadística práctica para ciencia de datos con R y Python</em> (Bruce, Bruce y Gedeck, 2.ª edición), la misma fuente de la semana pasada. Esta semana cierra la caja de herramientas para variables numéricas con los percentiles y el diagrama de caja (boxplot), y abre la caja de herramientas para variables categóricas: gráficos de barras y tablas de contingencia.</p>
<p>La media, la mediana y la desviación estándar que calculaste la semana pasada resumen una variable en un solo número. El boxplot va un paso más allá: resume la distribución completa en cinco puntos de referencia (el mínimo dentro de rango, el percentil 25, la mediana, el percentil 75 y el máximo dentro de rango) y señala aparte los valores atípicos. Es la herramienta que vas a usar todas las semanas de aquí en adelante para comparar la distribución de una variable numérica entre varios grupos de un vistazo, algo que un histograma por grupo hace mucho más difícil de leer.</p>
<p>Las variables categóricas no tienen media ni mediana: no puedes promediar “preventiva” y “correctiva”. Lo que sí puedes hacer es contar cuántas veces aparece cada categoría, y esa cuenta es la base de un gráfico de barras cuando hay una sola variable categórica, y de una tabla de contingencia cuando quieres cruzar dos.</p>
<p>El dataset guía sigue siendo <code>state.csv</code>, ya cargado la semana pasada. Para gráficos de barras y tablas de contingencia usas dos datasets nuevos del mismo repositorio del libro: los minutos de retraso acumulados por causa en el aeropuerto de Dallas-Fort Worth, y el historial de 450 961 préstamos de Lending Club con su calificación de riesgo y su estado de pago. Cierras con un caso integrador sobre los retrasos de seis aerolíneas, comparando boxplots agrupados por categoría.</p>
<p>Al terminar deberías poder:</p>
<ol type="1">
<li>Calcular percentiles con pandas e interpretar qué fracción de los datos queda por debajo y por encima de cada uno.</li>
<li>Construir un diagrama de caja a partir de percentiles y el IQR, explicar la regla que fija dónde termina cada bigote, e identificar valores atípicos con esa misma regla.</li>
<li>Construir un gráfico de barras para una variable categórica, distinguirlo de un histograma, y explicar por qué un gráfico circular casi nunca es la mejor opción.</li>
<li>Construir una tabla de contingencia entre dos variables categóricas con <code>pd.crosstab</code>, calcular porcentajes por fila, e interpretar el hallazgo que resulta.</li>
<li>Comparar la distribución de una variable numérica entre varias categorías con un boxplot agrupado, e identificar cuándo dos grupos no se superponen.</li>
</ol>
</section>
<section id="recapitulación-breve" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="recapitulación-breve"><span class="header-section-number">2</span> Recapitulación breve</h2>
<p><code>state</code> ya está en memoria desde la semana pasada. Si arrancas una sesión nueva, esta línea la recupera:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/gedeck/practical-statistics-for-data-scientists/master/data/state.csv"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>state <span class="op">=</span> pd.read_csv(url)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Recuerda las dos columnas numéricas: <code>Population</code> (población de cada uno de los 50 estados, censo 2010) y <code>Murder.Rate</code> (tasa de homicidios por cada 100 000 habitantes). Vas a trabajar <code>Population</code> conmigo y <code>Murder.Rate</code> por tu cuenta, igual que la semana pasada.</p>
</section>
<section id="percentiles" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="percentiles"><span class="header-section-number">3</span> Percentiles</h2>
<p>El percentil <span class="math inline">\(P\)</span> de una variable es el valor tal que aproximadamente el <span class="math inline">\(P\)</span>% de los datos queda por debajo de él. Los cuartiles son los percentiles 25, 50 y 75; el percentil 50 es la mediana que ya conoces.</p>
<p>Para calcularlo por interpolación lineal sobre la lista ordenada <span class="math inline">\(x_{(1)}, x_{(2)}, \ldots,
x_{(n)}\)</span>, se ubica primero una posición continua <span class="math inline">\(pos = P \times (n - 1)\)</span>, y se interpola entre los dos datos reales que rodean esa posición:</p>
<p><span class="math display">\[
\text{percentil}(P) = x_{(\lfloor pos \rfloor)} + \left(pos - \lfloor pos \rfloor\right) \times
\left(x_{(\lfloor pos \rfloor + 1)} - x_{(\lfloor pos \rfloor)}\right)
\]</span></p>
<p>Cuando <span class="math inline">\(pos\)</span> cae exactamente sobre un dato (por ejemplo, si <span class="math inline">\(P \times (n-1)\)</span> da un entero), el percentil es ese dato tal cual: la parte fraccionaria de la interpolación es cero.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>percentiles <span class="op">=</span> state[<span class="st">"Population"</span>].quantile([<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>])</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(percentiles)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>0.25    1833004.25
0.50    4436369.50
0.75    6680312.25
Name: Population, dtype: float64</code></pre>
<p><code>.quantile()</code> acepta un valor entre 0 y 1 (no entre 0 y 100) y usa exactamente esta interpolación por defecto. El percentil 0.5 coincide con la mediana que calculaste la semana pasada (4 436 369.5): son la misma medida, calculada con dos funciones distintas.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación en contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>El percentil 25 (1 833 004) dice que una cuarta parte de los 50 estados tiene menos de 1.83 millones de habitantes. El percentil 75 (6 680 312) dice que tres cuartas partes de los estados tienen menos de 6.68 millones, o, dicho al revés, que solo una cuarta parte supera esa cifra. Entre esos dos valores queda el 50% central de los estados: ni los más chicos ni los más grandes, el grupo de en medio.</p>
</div>
</div>
</section>
<section id="el-diagrama-de-caja-boxplot" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="el-diagrama-de-caja-boxplot"><span class="header-section-number">4</span> El diagrama de caja (boxplot)</h2>
<p>El diagrama de caja, propuesto por el estadístico John Tukey en 1977, resume una variable numérica completa en cinco puntos de referencia, calculados a partir de los percentiles que acabas de ver.</p>
<div class="diagrama">
<p><img src="imagenes/anatomia-boxplot.svg" class="img-fluid" alt="Diagrama de caja con sus partes rotuladas: la caja va del percentil 25 al percentil 75 con la mediana marcada adentro, cada bigote se extiende hasta el dato real mas alejado que sigue dentro de 1.5 veces el IQR desde el borde de la caja, y los puntos mas alla de ese limite se marcan aparte como atipicos."></p>
</div>
<p>La caja va del percentil 25 (<code>Q1</code>) al percentil 75 (<code>Q3</code>), con una línea marcando la mediana adentro. El ancho de la caja es exactamente el IQR que calculaste la semana pasada:</p>
<p><span class="math display">\[
\text{IQR} = Q_3 - Q_1
\]</span></p>
<p>Los bigotes son la parte que más se presta a confusión. <strong>No</strong> se extienden una distancia fija de 1.5 veces el IQR: se extienden hasta el dato real más alejado que sigue dentro de ese límite. El límite se calcula así:</p>
<p><span class="math display">\[
\text{límite inferior} = Q_1 - 1.5 \times \text{IQR} \qquad\qquad
\text{límite superior} = Q_3 + 1.5 \times \text{IQR}
\]</span></p>
<p>Cualquier dato entre esos dos límites queda cubierto por un bigote, hasta el más extremo de ellos. Cualquier dato fuera de ese rango se dibuja aparte, como un punto individual: es un valor atípico según esta regla. Matplotlib construye sus boxplots con esta misma convención.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>q1 <span class="op">=</span> state[<span class="st">"Population"</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>q3 <span class="op">=</span> state[<span class="st">"Population"</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> q3 <span class="op">-</span> q1</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>limite_inferior <span class="op">=</span> q1 <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>limite_superior <span class="op">=</span> q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Q1:"</span>, q1)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Q3:"</span>, q3)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"IQR:"</span>, iqr)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"limite inferior:"</span>, limite_inferior)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"limite superior:"</span>, limite_superior)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>atipicos <span class="op">=</span> state[(state[<span class="st">"Population"</span>] <span class="op">&lt;</span> limite_inferior) <span class="op">|</span> (state[<span class="st">"Population"</span>] <span class="op">&gt;</span> limite_superior)]</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atipicos[[<span class="st">"State"</span>, <span class="st">"Population"</span>]].sort_values(<span class="st">"Population"</span>, ascending<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>Q1: 1833004.25
Q3: 6680312.25
IQR: 4847308.0
limite inferior: -5437957.75
limite superior: 13951274.25
         State  Population
4   California    37253956
42       Texas    25145561
31    New York    19378102
8      Florida    18801310</code></pre>
<p>El IQR de <code>Population</code> es 4 847 308: exactamente el mismo número que calculaste la semana pasada con <code>.quantile(0.75) - .quantile(0.25)</code>. El límite inferior sale negativo, así que ningún estado puede quedar fuera por abajo (la población no puede ser negativa); el bigote inferior llega hasta Wyoming, el estado con menos habitantes. Por arriba, cuatro estados superan el límite de 13 951 274 y quedan marcados como atípicos: California, Texas, Nueva York y Florida. Son los mismos cuatro estados que más alejaban la media de la mediana la semana pasada.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>ax.boxplot(state[<span class="st">"Population"</span>] <span class="op">/</span> <span class="dv">1_000_000</span>, vert<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"población por estado (millones de habitantes)"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="diagrama">
<p><img src="imagenes/boxplot-poblacion.svg" class="img-fluid" alt="Diagrama de caja horizontal de la poblacion por estado en millones de habitantes, con la caja concentrada entre 1.8 y 6.7 millones y cuatro puntos atipicos hacia la derecha correspondientes a California, Texas, Nueva York y Florida."></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación en contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>La caja, angosta y pegada a la izquierda del gráfico, dice que la mayoría de los estados tiene una población relativamente baja y parecida entre sí. Los cuatro puntos sueltos a la derecha no son ruido ni un error de los datos: son estados reales, mucho más poblados que el resto, y el boxplot los separa visualmente en vez de dejar que estiren la escala del gráfico entero, como pasaría con un histograma de pocos contenedores.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejercicio: boxplot de <code>Murder.Rate</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Calcula los percentiles 25, 50 y 75 de <code>Murder.Rate</code>, el IQR, los límites del boxplot y los valores atípicos que resulten. Antes de correr el código, piensa: la semana pasada viste que <code>Murder.Rate</code> no tenía un atípico tan marcado como California. ¿Esperas cero atípicos, uno, o varios?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>percentiles_mr <span class="op">=</span> state[<span class="st">"Murder.Rate"</span>].quantile([<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(percentiles_mr)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>q1_mr <span class="op">=</span> state[<span class="st">"Murder.Rate"</span>].quantile(<span class="fl">0.25</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>q3_mr <span class="op">=</span> state[<span class="st">"Murder.Rate"</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>iqr_mr <span class="op">=</span> q3_mr <span class="op">-</span> q1_mr</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>limite_inf_mr <span class="op">=</span> q1_mr <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr_mr</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>limite_sup_mr <span class="op">=</span> q3_mr <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr_mr</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"IQR:"</span>, iqr_mr)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"limite inferior:"</span>, limite_inf_mr)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"limite superior:"</span>, limite_sup_mr)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>atipicos_mr <span class="op">=</span> state[(state[<span class="st">"Murder.Rate"</span>] <span class="op">&lt;</span> limite_inf_mr) <span class="op">|</span> (state[<span class="st">"Murder.Rate"</span>] <span class="op">&gt;</span> limite_sup_mr)]</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atipicos_mr[[<span class="st">"State"</span>, <span class="st">"Murder.Rate"</span>]])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>0.25    2.425
0.50    4.000
0.75    5.550
Name: Murder.Rate, dtype: float64
IQR: 3.125
limite inferior: -2.2625
limite superior: 10.2375
        State  Murder.Rate
17  Louisiana         10.3</code></pre>
<p>Un único atípico: Louisiana, con una tasa de 10.3, apenas por encima del límite superior de 10.24. Es coherente con lo que ya sabías: <code>Murder.Rate</code> tiene sesgo a la derecha, pero mucho más leve que <code>Population</code>, así que el boxplot marca un solo estado en el límite en vez de un grupo de cuatro muy por encima del resto.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="variables-categóricas-moda-y-gráficos-de-barras" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="variables-categóricas-moda-y-gráficos-de-barras"><span class="header-section-number">5</span> Variables categóricas: moda y gráficos de barras</h2>
<p>Una variable categórica no tiene percentiles ni boxplot: no hay un orden numérico entre “tormenta” y “falla mecánica” como causas de un retraso. Lo único que se puede hacer es contar cuántas veces aparece cada categoría. El valor con el conteo más alto es la moda, y esa cuenta, graficada, es un gráfico de barras.</p>
<p>El dataset de esta sección resume los minutos de retraso acumulados en el aeropuerto de Dallas-Fort Worth, agrupados por causa: problema del transportista (<code>Carrier</code>), control de tráfico aéreo (<code>ATC</code>), clima (<code>Weather</code>), seguridad (<code>Security</code>) y vuelo entrante retrasado (<code>Inbound</code>). Es una sola fila con una columna por causa; para tratarla como una variable categórica hay que transponerla.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>url_dfw <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/gedeck/practical-statistics-for-data-scientists/master/data/dfw_airline.csv"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dfw <span class="op">=</span> pd.read_csv(url_dfw)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dfw)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>causas <span class="op">=</span> dfw.transpose()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>causas.columns <span class="op">=</span> [<span class="st">"minutos"</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>causas[<span class="st">"porcentaje"</span>] <span class="op">=</span> (causas[<span class="st">"minutos"</span>] <span class="op">/</span> causas[<span class="st">"minutos"</span>].<span class="bu">sum</span>() <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(causas.sort_values(<span class="st">"minutos"</span>, ascending<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>    Carrier      ATC   Weather  Security    Inbound
0  64263.16  84856.5  11235.42    343.15  118427.82
            minutos  porcentaje
Inbound   118427.82        42.4
ATC        84856.50        30.4
Carrier    64263.16        23.0
Weather    11235.42         4.0
Security     343.15         0.1</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ax.bar(causas.index, causas[<span class="st">"minutos"</span>])</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"causa del retraso"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"minutos de retraso acumulados"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="diagrama">
<p><img src="imagenes/barras-causas-retraso.svg" class="img-fluid" alt="Grafico de barras con cinco causas de retraso de vuelos: retraso de vuelo entrante es la barra mas alta, seguida de control de trafico aereo, problema del transportista, clima, y seguridad como la barra mas baja, casi invisible."></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación en contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>La categoría más frecuente (la moda) es “Inbound”: el 42.4% de los minutos de retraso vienen de vuelos que ya llegaban tarde desde otro aeropuerto, no de un problema en Dallas-Fort Worth mismo. Junto con el control de tráfico aéreo (30.4%), estas dos causas explican más del 70% del retraso total. La seguridad, en cambio, es prácticamente irrelevante (0.1%): en un análisis real, ahí no vale la pena invertir esfuerzo de mejora.</p>
</div>
</div>
<p><strong>Gráfico de barras contra histograma.</strong> Los dos se parecen (barras verticales sobre un eje), y por eso se confunden. La diferencia está en el eje horizontal: en un histograma, el eje es numérico y continuo, y las barras van pegadas unas a otras porque representan contenedores que cubren todo el rango sin huecos. En un gráfico de barras, el eje muestra categorías sin orden numérico, y las barras van separadas porque no hay continuidad entre “clima” y “seguridad”: podrías reordenarlas sin que el gráfico pierda sentido, algo que no puedes hacer con los contenedores de un histograma.</p>
<p><strong>Por qué no un gráfico circular (de pastel).</strong> Es una alternativa común para mostrar proporciones entre categorías, pero el ojo humano compara longitudes y posiciones mucho mejor de lo que compara ángulos y áreas. Con más de dos o tres categorías, un gráfico circular hace difícil saber cuál porción es más grande sin leer las etiquetas de porcentaje una por una; un gráfico de barras ordenado de mayor a menor responde esa pregunta con una mirada.</p>
</section>
<section id="tablas-de-contingencia" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="tablas-de-contingencia"><span class="header-section-number">6</span> Tablas de contingencia</h2>
<p>Cuando quieres cruzar dos variables categóricas (no resumir una sola), la herramienta es la tabla de contingencia: un recuento de cuántas observaciones caen en cada combinación posible de las dos variables.</p>
<p>El dataset de esta sección trae 450 961 préstamos de Lending Club, cada uno con su calificación de riesgo (<code>grade</code>, de A a G, siendo A la más segura) y su estado (<code>status</code>: pagado por completo, vigente, atrasado o cancelado por incumplimiento).</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>url_lc <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/gedeck/practical-statistics-for-data-scientists/master/data/lc_loans.csv"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>lc <span class="op">=</span> pd.read_csv(url_lc)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(lc.shape)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(lc.head())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>(450961, 2)
        status grade
0   Fully Paid     B
1  Charged Off     C
2   Fully Paid     C
3   Fully Paid     C
4      Current     B</code></pre>
<p><code>pd.crosstab</code> construye la tabla de contingencia: una fila por cada valor de <code>grade</code>, una columna por cada valor de <code>status</code>, y en cada celda el conteo de préstamos con esa combinación exacta.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="op">=</span> pd.crosstab(lc[<span class="st">"grade"</span>], lc[<span class="st">"status"</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>status  Charged Off  Current  Fully Paid  Late
grade
A              1562    50051       20408   469
B              5302    93852       31160  2056
C              6023    88928       23147  2777
D              5007    53281       13681  2308
E              2842    24639        5949  1374
F              1526     8444        2328   606
G               409     1990         643   199</code></pre>
<p>Con <code>margins=True</code> se agregan la suma de cada fila y de cada columna, para verificar que los conteos cuadran con el total del dataset:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tabla_con_margen <span class="op">=</span> pd.crosstab(lc[<span class="st">"grade"</span>], lc[<span class="st">"status"</span>], margins<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla_con_margen)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>status  Charged Off  Current  Fully Paid  Late     All
grade
A              1562    50051       20408   469   72490
B              5302    93852       31160  2056  132370
C              6023    88928       23147  2777  120875
D              5007    53281       13681  2308   74277
E              2842    24639        5949  1374   34804
F              1526     8444        2328   606   12904
G               409     1990         643   199    3241
All           22671   321185       97316  9789  450961</code></pre>
<p>Los conteos por sí solos no responden la pregunta que más importa: ¿la calificación de riesgo predice el resultado del préstamo? Para verlo hay que convertir cada fila a porcentaje, dividiendo entre el total de esa fila (no entre el total de la tabla).</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>porcentaje_fila <span class="op">=</span> (tabla.div(tabla.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>), axis<span class="op">=</span><span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(porcentaje_fila)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>status  Charged Off  Current  Fully Paid  Late
grade
A               2.2     69.0        28.2   0.6
B               4.0     70.9        23.5   1.6
C               5.0     73.6        19.1   2.3
D               6.7     71.7        18.4   3.1
E               8.2     70.8        17.1   3.9
F              11.8     65.4        18.0   4.7
G              12.6     61.4        19.8   6.1</code></pre>
<div class="diagrama">
<p><img src="imagenes/contingencia-lectura.svg" class="img-fluid" alt="Tabla de contingencia entre grado del credito y estado del prestamo, con una flecha que muestra como se divide una fila entre su propia suma para obtener el porcentaje de esa fila, comparando el 0.6 por ciento de atraso en el grado A contra el 6.1 por ciento en el grado G."></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación en contexto
</div>
</div>
<div class="callout-body-container callout-body">
<p>El patrón es consistente en las cuatro columnas: a medida que la calificación baja de A a G, el porcentaje de préstamos atrasados (<code>Late</code>) sube de 0.6% a 6.1%, y el porcentaje cancelado por incumplimiento (<code>Charged Off</code>) sube de 2.2% a 12.6%. Al mismo tiempo, el porcentaje pagado por completo baja de 28.2% a 19.8%. La calificación de riesgo, calculada antes de que el préstamo se otorgue, sí anticipa cómo termina: es la evidencia de que el sistema de calificación está haciendo su trabajo, no un adorno del reporte.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejercicio: la calificación más baja
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Calcula, solo para los préstamos con la calificación más baja que aparece en los datos, qué porcentaje tiene estado <code>Late</code>. Verifica que coincide con la fila correspondiente de la tabla de porcentajes que ya calculaste.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solución
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>grado_mas_bajo <span class="op">=</span> lc[lc[<span class="st">"grade"</span>] <span class="op">==</span> <span class="st">"G"</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(grado_mas_bajo))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>porcentaje_late <span class="op">=</span> (grado_mas_bajo[<span class="st">"status"</span>] <span class="op">==</span> <span class="st">"Late"</span>).mean() <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(porcentaje_late, <span class="dv">1</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>3241
6.1</code></pre>
<p>3241 préstamos tienen calificación G, la más baja del dataset. De esos, 6.1% están en <code>Late</code>, exactamente el mismo número que aparece en la última fila de <code>porcentaje_fila</code>. Calcularlo de las dos formas (filtrando y promediando una condición booleana, o leyendo la tabla ya armada) sirve para confirmar que entiendes de dónde sale cada celda de la tabla de contingencia, no solo para leerla.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="caso-integrador-retrasos-por-aerolínea" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="caso-integrador-retrasos-por-aerolínea"><span class="header-section-number">7</span> Caso integrador: retrasos por aerolínea</h2>
<p>Para cerrar, comparas la distribución de una variable numérica entre varias categorías: el porcentaje de minutos de retraso atribuible directamente a la aerolínea (<code>pct_carrier_delay</code>), para 33 468 vuelos de seis aerolíneas distintas. Un boxplot agrupado pone un boxplot por categoría, uno al lado del otro, sobre el mismo eje.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>url_air <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/gedeck/practical-statistics-for-data-scientists/master/data/airline_stats.csv"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>air <span class="op">=</span> pd.read_csv(url_air)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(air.shape)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(air[<span class="st">"airline"</span>].unique())</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>resumen <span class="op">=</span> air.groupby(<span class="st">"airline"</span>)[<span class="st">"pct_carrier_delay"</span>].agg(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"median"</span>, <span class="kw">lambda</span> s: s.quantile(<span class="fl">0.25</span>), <span class="kw">lambda</span> s: s.quantile(<span class="fl">0.75</span>)]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>resumen.columns <span class="op">=</span> [<span class="st">"mediana"</span>, <span class="st">"Q1"</span>, <span class="st">"Q3"</span>]</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(resumen.sort_values(<span class="st">"mediana"</span>).<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>(33468, 4)
['American' 'Alaska' 'Jet Blue' 'Delta' 'United' 'Southwest']
           mediana    Q1     Q3
airline
Alaska        3.23  1.94   4.69
Delta         5.55  3.81   7.82
United        6.45  4.03   9.63
Southwest     6.96  5.07   9.35
Jet Blue      7.66  5.34  10.28
American      8.43  6.34  10.99</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>air.boxplot(column<span class="op">=</span><span class="st">"pct_carrier_delay"</span>, by<span class="op">=</span><span class="st">"airline"</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.6</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="diagrama">
<p><img src="imagenes/boxplot-aerolineas.svg" class="img-fluid" alt="Seis diagramas de caja, uno por aerolinea, ordenados de menor a mayor mediana de porcentaje de retraso atribuible a la aerolinea: Alaska con la caja mas baja, seguida de Delta, United, Southwest, Jet Blue y American con la caja mas alta."></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejercicio de cierre: redacta la conclusión
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Compara el cuartil 75 (<code>Q3</code>) de Alaska con el cuartil 25 (<code>Q1</code>) de American en la tabla de arriba. ¿Qué significa, en términos del boxplot, que uno sea menor que el otro? Redacta la conclusión en dos o tres oraciones, como si se la entregaras a un gerente de operaciones que decide con qué aerolíneas mantener un acuerdo de nivel de servicio.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Una posible respuesta
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El <code>Q3</code> de Alaska es 4.69 y el <code>Q1</code> de American es 6.34: el 75% de los vuelos de Alaska con más retraso atribuible a la aerolínea todavía queda por debajo del 25% de los vuelos de American con menos retraso. Dicho con el boxplot: la caja completa de Alaska queda por debajo de la caja completa de American, sin superposición entre ellas. No es un caso aislado ni una diferencia de un par de vuelos: es una diferencia sistemática entre las dos aerolíneas en la variable medida, visible de un vistazo en el gráfico sin necesidad de leer una sola tabla de números.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="ejercicio-final-constrúyelo-tú-de-principio-a-fin" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="ejercicio-final-constrúyelo-tú-de-principio-a-fin"><span class="header-section-number">8</span> Ejercicio final: constrúyelo tú, de principio a fin</h2>
<p>Todo lo anterior te dio el dataset, las preguntas y hasta la solución. Este último ejercicio no trae nada de eso: te toca buscar los datos, decidir qué preguntar y justificar cada respuesta con lo que aprendiste esta semana. No tiene solución en esta guía y no se evalúa, pero tráelo resuelto (o avanzado) a la próxima sesión.</p>
<section id="paso-1.-consigue-un-dataset-con-al-menos-una-variable-numérica-y-una-categórica" class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-consigue-un-dataset-con-al-menos-una-variable-numérica-y-una-categórica">Paso 1. Consigue un dataset con al menos una variable numérica y una categórica</h3>
<p>Elige uno de estos dos caminos.</p>
<p><strong>Camino A: el dataset de respaldo del libro</strong>, ya usado la semana pasada: <code>kc_tax.csv.gz</code>, con el valor catastral, el área construida y el código postal de casi 500 000 viviendas del condado de King. <code>ZipCode</code> es la variable categórica (aunque se vea como número, no tiene sentido promediarlo); <code>TaxAssessedValue</code> o <code>SqFtTotLiving</code> son las numéricas.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>kc_tax <span class="op">=</span> pd.read_csv(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://raw.githubusercontent.com/gedeck/practical-statistics-for-data-scientists/master/data/kc_tax.csv.gz"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    compression<span class="op">=</span><span class="st">"gzip"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(kc_tax.shape)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(kc_tax.head())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Camino B: un dataset que tú busques</strong>, en <a href="https://www.datos.gov.co/">datos.gov.co</a>, el <a href="https://datos.bancomundial.org/">portal de datos abiertos del Banco Mundial</a>, <a href="https://www.kaggle.com/datasets">Kaggle</a> o el <a href="https://archive.ics.uci.edu/">UCI Machine Learning Repository</a>. Debe tener al menos una variable numérica y una categórica con pocas categorías (menos de 10, para que el boxplot agrupado o el gráfico de barras sean legibles).</p>
</section>
<section id="paso-2.-formula-tus-propias-preguntas" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-formula-tus-propias-preguntas">Paso 2. Formula tus propias preguntas</h3>
<p>Escribe al menos dos preguntas: una que se responda con un boxplot o percentiles de una variable numérica (¿hay atípicos? ¿cuál es el rango del 50% central?), y otra que se responda con un gráfico de barras o una tabla de contingencia de una o dos variables categóricas (¿qué categoría es más frecuente? ¿la distribución de la variable numérica cambia según la categoría?).</p>
</section>
<section id="paso-3.-responde-y-justifica-cada-una" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-responde-y-justifica-cada-una">Paso 3. Responde y justifica cada una</h3>
<p>Para cada pregunta, calcula la medida o el gráfico que la responde, y redacta la conclusión en dos o tres oraciones, en el mismo tono ejecutivo del caso de las aerolíneas: qué significa para alguien que va a decidir con ese resultado, no solo el número o el gráfico en sí.</p>
</section>
<section id="paso-4.-si-tienes-una-variable-numérica-y-una-categórica-juntas-crúzalas" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-si-tienes-una-variable-numérica-y-una-categórica-juntas-crúzalas">Paso 4. Si tienes una variable numérica y una categórica juntas, crúzalas</h3>
<p>Construye un boxplot agrupado (como el de las aerolíneas) o, si tus dos variables son ambas categóricas, una tabla de contingencia con porcentajes por fila. Interpreta si hay una diferencia sistemática entre los grupos o si se superponen sin un patrón claro.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Antes de la próxima sesión
</div>
</div>
<div class="callout-body-container callout-body">
<p>Revisa que tu trabajo cumpla las tres condiciones que pide el módulo para cualquier entrega: <strong>reproducible</strong>, <strong>trazable</strong> y <strong>ejecutiva</strong> (ver la presentación del módulo).</p>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">9</span> Errores frecuentes</h2>
<div class="error-caso">
<p><span class="etiqueta">Error 1</span></p>
<section id="confundir-un-gráfico-de-barras-con-un-histograma" class="level3">
<h3 class="anchored" data-anchor-id="confundir-un-gráfico-de-barras-con-un-histograma">Confundir un gráfico de barras con un histograma</h3>
<p><strong>Causa.</strong> Los dos son barras verticales sobre un eje, y con pocas categorías o pocos contenedores se ven parecidos a simple vista.</p>
<p><strong>Solución.</strong> Pregúntate qué representa el eje horizontal. Si son categorías sin orden numérico (causas de retraso, tipos de intervención), es un gráfico de barras, y las barras van separadas. Si es un rango numérico dividido en contenedores contiguos, es un histograma, y las barras van pegadas.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 2</span></p>
<section id="asumir-que-el-bigote-del-boxplot-está-siempre-a-1.5-veces-el-iqr" class="level3">
<h3 class="anchored" data-anchor-id="asumir-que-el-bigote-del-boxplot-está-siempre-a-1.5-veces-el-iqr">Asumir que el bigote del boxplot está siempre a 1.5 veces el IQR</h3>
<p><strong>Causa.</strong> La fórmula del límite (<span class="math inline">\(Q_3 + 1.5 \times \text{IQR}\)</span>) es fácil de recordar mal como “el bigote llega hasta ahí”, cuando en realidad ese número es solo un límite, no la posición real del bigote.</p>
<p><strong>Solución.</strong> El bigote termina en el dato real más extremo que sigue dentro de ese límite, no en el límite mismo. Con <code>Population</code>, el límite superior es 13 951 274, pero el bigote real llega solo hasta Illinois, con 12 830 632 habitantes: el siguiente dato (California) ya está fuera del límite, así que se dibuja aparte como atípico, y el bigote se queda en el último dato real que sí calificó.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 3</span></p>
<section id="leer-un-porcentaje-de-una-tabla-de-contingencia-sin-saber-sobre-qué-se-calculó" class="level3">
<h3 class="anchored" data-anchor-id="leer-un-porcentaje-de-una-tabla-de-contingencia-sin-saber-sobre-qué-se-calculó">Leer un porcentaje de una tabla de contingencia sin saber sobre qué se calculó</h3>
<p><strong>Causa.</strong> Una tabla de contingencia admite porcentajes por fila, por columna o sobre el total, y dan números distintos. Leer “12.6%” sin saber cuál de los tres es la tabla lleva a una conclusión equivocada.</p>
<p><strong>Solución.</strong> Antes de interpretar un porcentaje, identifica el denominador. En esta guía, “12.6% de <code>Charged Off</code> en el grado G” significa 12.6% <em>de los préstamos del grado G</em> (porcentaje por fila), no 12.6% de todos los préstamos cancelados del dataset ni 12.6% de todo el dataset completo. Cambiar el eje de la división cambia lo que dice el número.</p>
</section>
</div>
</section>
<section id="lista-de-chequeo-de-la-semana" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="lista-de-chequeo-de-la-semana"><span class="header-section-number">10</span> Lista de chequeo de la semana</h2>
<div class="checklist">
<p><strong>Antes de la próxima sesión</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Puedes calcular un percentil con <code>.quantile()</code> y explicar qué fracción de los datos queda por debajo de ese valor</label></li>
<li><label><input type="checkbox">Puedes explicar de memoria la regla que fija dónde termina cada bigote de un boxplot, y por qué no es una distancia fija</label></li>
<li><label><input type="checkbox">Resolviste los dos ejercicios intermedios (boxplot de <code>Murder.Rate</code>, calificación más baja de <code>lc_loans</code>) antes de revisar la solución, no después</label></li>
<li><label><input type="checkbox">Puedes explicar la diferencia entre un gráfico de barras y un histograma con tus propias palabras</label></li>
<li><label><input type="checkbox">Sabes construir una tabla de contingencia con <code>pd.crosstab</code> y calcular porcentajes por fila</label></li>
<li><label><input type="checkbox">Completaste el caso integrador de <code>airline_stats.csv</code> con tu propia conclusión escrita</label></li>
<li><label><input type="checkbox">Avanzaste el ejercicio final: al menos el Paso 1 (dataset elegido) y el Paso 2 (tus preguntas escritas) antes de la próxima sesión</label></li>
</ul>
</div>
</section>
<section id="lo-que-viene" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="lo-que-viene"><span class="header-section-number">11</span> Lo que viene</h2>
<ul>
<li><strong>Semana 5.</strong> Vas a explorar relaciones entre dos variables numéricas con gráficos de dispersión, y relaciones condicionadas a una tercera variable con gráficos condicionales. Cierras la Unidad 1 con un informe exploratorio completo (30% de la nota).</li>
<li><strong>Semana 6.</strong> Empieza la Unidad 2: variables aleatorias, espacio muestral y función de distribución.</li>
</ul>
</section>
<section id="recursos" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="recursos"><span class="header-section-number">12</span> Recursos</h2>
<ul>
<li>Bruce, P., Bruce, A. y Gedeck, P. <em>Estadística práctica para ciencia de datos con R y Python.</em> 2.ª edición, MARCOMBO, 2022. Capítulo 1: “Análisis exploratorio de datos”. Fuente de esta guía.</li>
<li>Datasets de esta guía, del repositorio de datos del libro: <a href="https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/data/state.csv"><code>state.csv</code></a>, <a href="https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/data/dfw_airline.csv"><code>dfw_airline.csv</code></a>, <a href="https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/data/lc_loans.csv"><code>lc_loans.csv</code></a> y <a href="https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/data/airline_stats.csv"><code>airline_stats.csv</code></a></li>
<li>Documentación de <code>pandas.DataFrame.quantile</code>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html">pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html</a></li>
<li>Documentación de <code>pandas.crosstab</code>: <a href="https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html">pandas.pydata.org/docs/reference/api/pandas.crosstab.html</a></li>
</ul>
<div class="pie-doc">
<p>Estadística para Analítica. Institución Universitaria Pascual Bravo. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Opus 5 de Anthropic. Todo el contenido fue revisado y validado. Las salidas de terminal y los gráficos son reales, producidos al ejecutar estos mismos programas durante la preparación del material.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-pascual-b-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
<p>Institución Universitaria Pascual Bravo. Facultad de Ingeniería</p>
</div>
    <div class="nav-footer-right">
<p>Semestre 2026-02</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>