<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Semana 2. Sintaxis, variables y consola – Clases Pascual Bravo 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-63bd06c2c145d35a53f198c60a9c2611.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../herramientas-programacion-1/semana-01/index.html">Unidad 1. Aplicaciones de consola con un IDE</a></li><li class="breadcrumb-item"><a href="../../herramientas-programacion-1/semana-02/index.html">Semana 2. Sintaxis, variables y consola</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Clases Pascual Bravo 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../herramientas-programacion-1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Aplicaciones de consola con un IDE</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../herramientas-programacion-1/semana-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 1. Entorno, Git y GitHub</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../herramientas-programacion-1/semana-02/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Semana 2. Sintaxis, variables y consola</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#lo-que-vas-a-lograr" id="toc-lo-que-vas-a-lograr" class="nav-link active" data-scroll-target="#lo-que-vas-a-lograr"><span class="header-section-number">1</span> Lo que vas a lograr</a></li>
  <li><a href="#anatomía-de-un-programa-con-sentencias-de-nivel-superior" id="toc-anatomía-de-un-programa-con-sentencias-de-nivel-superior" class="nav-link" data-scroll-target="#anatomía-de-un-programa-con-sentencias-de-nivel-superior"><span class="header-section-number">2</span> Anatomía de un programa con sentencias de nivel superior</a></li>
  <li><a href="#sintaxis-básica-del-lenguaje" id="toc-sintaxis-básica-del-lenguaje" class="nav-link" data-scroll-target="#sintaxis-básica-del-lenguaje"><span class="header-section-number">3</span> Sintaxis básica del lenguaje</a>
  <ul class="collapse">
  <li><a href="#convenciones-de-nombres" id="toc-convenciones-de-nombres" class="nav-link" data-scroll-target="#convenciones-de-nombres">Convenciones de nombres</a></li>
  </ul></li>
  <li><a href="#tipos-de-variables" id="toc-tipos-de-variables" class="nav-link" data-scroll-target="#tipos-de-variables"><span class="header-section-number">4</span> Tipos de variables</a>
  <ul class="collapse">
  <li><a href="#tipos-por-valor-y-tipos-por-referencia" id="toc-tipos-por-valor-y-tipos-por-referencia" class="nav-link" data-scroll-target="#tipos-por-valor-y-tipos-por-referencia">Tipos por valor y tipos por referencia</a></li>
  <li><a href="#tipos-numéricos-cuál-usar-y-cuándo" id="toc-tipos-numéricos-cuál-usar-y-cuándo" class="nav-link" data-scroll-target="#tipos-numéricos-cuál-usar-y-cuándo">Tipos numéricos: cuál usar y cuándo</a></li>
  <li><a href="#caracteres-texto-y-valores-lógicos" id="toc-caracteres-texto-y-valores-lógicos" class="nav-link" data-scroll-target="#caracteres-texto-y-valores-lógicos">Caracteres, texto y valores lógicos</a></li>
  <li><a href="#var-y-el-tipo-explícito" id="toc-var-y-el-tipo-explícito" class="nav-link" data-scroll-target="#var-y-el-tipo-explícito"><code>var</code> y el tipo explícito</a></li>
  <li><a href="#valores-por-defecto" id="toc-valores-por-defecto" class="nav-link" data-scroll-target="#valores-por-defecto">Valores por defecto</a></li>
  </ul></li>
  <li><a href="#entrada-y-salida-por-consola" id="toc-entrada-y-salida-por-consola" class="nav-link" data-scroll-target="#entrada-y-salida-por-consola"><span class="header-section-number">5</span> Entrada y salida por consola</a>
  <ul class="collapse">
  <li><a href="#qué-significa-el-signo-de-interrogación-en-string" id="toc-qué-significa-el-signo-de-interrogación-en-string" class="nav-link" data-scroll-target="#qué-significa-el-signo-de-interrogación-en-string">Qué significa el signo de interrogación en <code>string?</code></a></li>
  </ul></li>
  <li><a href="#conversión-de-tipos-convert-parse-y-tryparse" id="toc-conversión-de-tipos-convert-parse-y-tryparse" class="nav-link" data-scroll-target="#conversión-de-tipos-convert-parse-y-tryparse"><span class="header-section-number">6</span> Conversión de tipos: <code>Convert</code>, <code>Parse</code> y <code>TryParse</code></a></li>
  <li><a href="#caso-de-uso-el-primer-registro-del-sistema-de-gestión" id="toc-caso-de-uso-el-primer-registro-del-sistema-de-gestión" class="nav-link" data-scroll-target="#caso-de-uso-el-primer-registro-del-sistema-de-gestión"><span class="header-section-number">7</span> Caso de uso: el primer registro del sistema de gestión</a></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">8</span> Errores frecuentes</a></li>
  <li><a href="#lista-de-verificación-de-la-semana" id="toc-lista-de-verificación-de-la-semana" class="nav-link" data-scroll-target="#lista-de-verificación-de-la-semana"><span class="header-section-number">9</span> Lista de verificación de la semana</a></li>
  <li><a href="#trabajo-independiente" id="toc-trabajo-independiente" class="nav-link" data-scroll-target="#trabajo-independiente"><span class="header-section-number">10</span> Trabajo independiente</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">11</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../herramientas-programacion-1/semana-01/index.html">Unidad 1. Aplicaciones de consola con un IDE</a></li><li class="breadcrumb-item"><a href="../../herramientas-programacion-1/semana-02/index.html">Semana 2. Sintaxis, variables y consola</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Semana 2. Sintaxis, variables y consola</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<tbody>
<tr class="odd">
<td>Asignatura</td>
<td>Herramientas de Programación I (ET0047)</td>
</tr>
<tr class="even">
<td>Programa</td>
<td>Tecnología en Desarrollo de Software</td>
</tr>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Aplicaciones de consola con un IDE</td>
</tr>
<tr class="even">
<td>Dedicación</td>
<td>4 horas de encuentro sincrónico y 8 de trabajo independiente</td>
</tr>
</tbody>
</table>
</div>
<p>Esta guía se probó con el SDK de .NET <strong>10.0.302</strong>. Si <code>dotnet --version</code> te muestra un número mayor dentro de la misma línea 10, el material funciona igual.</p>
<section id="lo-que-vas-a-lograr" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="lo-que-vas-a-lograr"><span class="header-section-number">1</span> Lo que vas a lograr</h2>
<p>En la Semana 1 dejaste <code>HolaPascual</code> ejecutando y publicado en GitHub. Esta semana abres ese mismo tipo de proyecto y aprendes de qué está hecho por dentro: cómo se organiza un programa de C#, qué tipos de datos existen para representar la información y cómo entra y sale esa información por la consola.</p>
<p>Objetivos concretos:</p>
<ol type="1">
<li>Explicar la estructura de un archivo <code>Program.cs</code> con sentencias de nivel superior.</li>
<li>Aplicar la sintaxis básica del lenguaje: sentencias, bloques, comentarios y convenciones de nombres.</li>
<li>Elegir el tipo de variable correcto según el dato que representa: enteros, reales, texto, caracteres y valores lógicos.</li>
<li>Leer datos por consola y convertir el texto que devuelve <code>Console.ReadLine</code> al tipo que necesitas, sin que un dato inválido detenga el programa.</li>
</ol>
<p><a href="presentacion-sintaxis-variables.html" class="btn btn-primary" role="button">Abrir la presentación de la sesión</a></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Opcional: los acentos en la consola
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la Semana 1 quedó pendiente el error de los acentos en la consola de Windows. La causa es que la consola usa una página de códigos distinta a la codificación UTF-8 del archivo fuente. Este curso deja la consola con su configuración por defecto y evita tildes y eñes en lo que imprime, así que no vas a necesitar nada especial para seguir el material.</p>
<p>Si prefieres ver los acentos en tu propia consola, agrega esta línea al inicio del programa, antes de la primera instrucción que escriba texto:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">OutputEncoding</span> <span class="op">=</span> System<span class="op">.</span><span class="fu">Text</span><span class="op">.</span><span class="fu">Encoding</span><span class="op">.</span><span class="fu">UTF8</span><span class="op">;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"Programación en C#: tildes, eñes y signos como el guion."</span><span class="op">);</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>Programación en C#: tildes, eñes y signos como el guion.</code></pre>
<p>Es opcional: ningún ejercicio del curso lo exige.</p>
</div>
</div>
</section>
<section id="anatomía-de-un-programa-con-sentencias-de-nivel-superior" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="anatomía-de-un-programa-con-sentencias-de-nivel-superior"><span class="header-section-number">2</span> Anatomía de un programa con sentencias de nivel superior</h2>
<p>Desde <code>dotnet new console</code>, el <code>Program.cs</code> que generó el SDK no tiene una clase <code>Program</code> ni un método <code>Main</code> visibles. Eso no significa que no existan: el compilador los genera por ti a partir de lo que escribes. A este estilo se le llama <strong>sentencias de nivel superior</strong> (<em>top-level statements</em>), y es la forma recomendada para escribir programas nuevos en C#.</p>
<p>Un archivo con sentencias de nivel superior se organiza en tres bloques, en este orden:</p>
<div class="diagrama">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="imagenes/anatomia-programa.svg" class="img-fluid figure-img" alt="Anatomia de un Program.cs: directivas using arriba, sentencias de nivel superior en el centro, definiciones de tipos opcionales al final, y el Main que genera el compilador"></p>
<figcaption>Un archivo Program.cs con sentencias de nivel superior se organiza en directivas using, el cuerpo del programa y, al final, las definiciones de tipos.</figcaption>
</figure>
</div>
</div>
<ol type="1">
<li><strong>Directivas <code>using</code></strong>, si necesitas una biblioteca que no está entre las que <code>.NET</code> importa de forma implícita (<code>ImplicitUsings</code> en el <code>.csproj</code>, que ya viste en la Semana 1).</li>
<li><strong>Las sentencias de nivel superior</strong>, que son el cuerpo real de tu programa. Van directamente en la raíz del archivo, sin envolverlas en una clase ni en un método.</li>
<li><strong>Definiciones de tipos</strong>, si el archivo también declara una clase o un <code>struct</code>. Deben ir después de las sentencias de nivel superior, nunca antes.</li>
</ol>
<p>Solo puede haber <strong>un archivo del proyecto</strong> con sentencias de nivel superior. Cuando el proyecto crezca y necesites varias clases en archivos separados (a partir de la Unidad 3), esos archivos adicionales no llevan sentencias de nivel superior: solo definiciones de tipos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Qué genera el compilador por dentro
</div>
</div>
<div class="callout-body-container callout-body">
<p>El compilador convierte tus sentencias de nivel superior en un método <code>Main</code> real. La firma exacta depende de si usas <code>return</code> o <code>await</code> en el cuerpo:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tu código usa</th>
<th>Firma que genera el compilador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ni <code>return</code> ni <code>await</code></td>
<td><code>static void Main(string[] args)</code></td>
</tr>
<tr class="even">
<td>Solo <code>return</code></td>
<td><code>static int Main(string[] args)</code></td>
</tr>
<tr class="odd">
<td>Solo <code>await</code></td>
<td><code>static async Task Main(string[] args)</code></td>
</tr>
<tr class="even">
<td><code>return</code> y <code>await</code></td>
<td><code>static async Task&lt;int&gt; Main(string[] args)</code></td>
</tr>
</tbody>
</table>
<p>No necesitas escribir esa firma. La vas a reconocer cuando en la Unidad 3 vuelvas a un <code>Main</code> explícito para organizar un proyecto más grande.</p>
</div>
</div>
<p>También tienes disponible la variable <code>args</code>, con los argumentos que reciba tu programa desde la línea de comandos. Nunca es <code>null</code>: si no pasaste ninguno, <code>args.Length</code> vale cero.</p>
</section>
<section id="sintaxis-básica-del-lenguaje" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sintaxis-básica-del-lenguaje"><span class="header-section-number">3</span> Sintaxis básica del lenguaje</h2>
<p>C# comparte varias reglas con el pseudocódigo que ya escribiste en Fundamentos de Programación, más un conjunto de símbolos que el compilador exige de forma estricta.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Regla</th>
<th>En C#</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fin de sentencia</td>
<td>Punto y coma <code>;</code> al final de cada instrucción</td>
</tr>
<tr class="even">
<td>Bloque de código</td>
<td>Llaves <code>{ }</code>. Todo lo que agrupas (el cuerpo de una función, de un <code>if</code>, de un ciclo) va entre ellas</td>
</tr>
<tr class="odd">
<td>Comentario de una línea</td>
<td><code>// texto</code>, desde ahí hasta el final del renglón</td>
</tr>
<tr class="even">
<td>Comentario de varias líneas</td>
<td><code>/* texto */</code>, puede abarcar varios renglones</td>
</tr>
<tr class="odd">
<td>Mayúsculas y minúsculas</td>
<td>El lenguaje distingue: <code>precio</code> y <code>Precio</code> son variables distintas</td>
</tr>
<tr class="even">
<td>Espacios e indentación</td>
<td>No afectan la ejecución, pero sí la lectura. Este curso indenta con 4 espacios</td>
</tr>
</tbody>
</table>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Esto es un comentario de una linea.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> cantidad <span class="op">=</span> <span class="dv">5</span><span class="op">;</span>   <span class="co">// el punto y coma cierra la sentencia</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">/* Esto es un comentario</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">   de varias lineas. */</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">if</span> <span class="op">(</span>cantidad <span class="op">&gt;</span> <span class="dv">0</span><span class="op">)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"Hay existencias."</span><span class="op">);</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Olvidar el punto y coma o dejar una llave sin cerrar es, con diferencia, el error más común de las primeras semanas. El compilador señala la línea siguiente a la del error real, así que si un mensaje no tiene sentido, revisa primero la línea de arriba.</p>
<section id="convenciones-de-nombres" class="level3">
<h3 class="anchored" data-anchor-id="convenciones-de-nombres">Convenciones de nombres</h3>
<p>C# no obliga un estilo de nombres, pero la comunidad y Microsoft usan uno consistente que este curso sigue desde ya:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Convención</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variables y parámetros</td>
<td><code>camelCase</code>: primera palabra en minúscula, las siguientes con inicial mayúscula</td>
<td><code>precioUnitario</code>, <code>nombreProducto</code></td>
</tr>
<tr class="even">
<td>Clases, métodos y tipos propios</td>
<td><code>PascalCase</code>: todas las palabras con inicial mayúscula</td>
<td><code>Producto</code>, <code>CalcularTotal</code></td>
</tr>
<tr class="odd">
<td>Constantes</td>
<td><code>PascalCase</code> también, en este curso</td>
<td><code>StockMinimo</code></td>
</tr>
</tbody>
</table>
<p>Un nombre de variable debe decir qué representa. <code>cantidad</code> comunica más que <code>c</code>, y <code>cantidadEnInventario</code> más que <code>cantidad</code> cuando el programa maneja varias cantidades a la vez.</p>
</section>
</section>
<section id="tipos-de-variables" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="tipos-de-variables"><span class="header-section-number">4</span> Tipos de variables</h2>
<p>Cada variable en C# tiene un tipo fijo, decidido cuando la declaras. El compilador impide mezclar tipos incompatibles antes de que el programa llegue a ejecutarse: es lo que se llama <strong>tipado fuerte</strong>, y es una de las diferencias más notorias frente al pseudocódigo de Fundamentos de Programación.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">5</span><span class="op">;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> esValido <span class="op">=</span> <span class="kw">true</span><span class="op">;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> total <span class="op">=</span> a <span class="op">+</span> <span class="dv">2</span><span class="op">;</span>        <span class="co">// correcto</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">// int error = a + esValido;   // el compilador lo rechaza: no se puede sumar int y bool</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<section id="tipos-por-valor-y-tipos-por-referencia" class="level3">
<h3 class="anchored" data-anchor-id="tipos-por-valor-y-tipos-por-referencia">Tipos por valor y tipos por referencia</h3>
<p>Todos los tipos de C# caen en una de dos categorías, y la diferencia importa desde ya porque determina qué pasa cuando copias una variable en otra.</p>
<div class="diagrama">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="imagenes/tipos-valor-vs-referencia.svg" class="img-fluid figure-img" alt="Comparacion entre tipos por valor, con copias independientes, y tipos por referencia, donde dos variables apuntan al mismo objeto"></p>
<figcaption>Los tipos por valor guardan el dato directamente y cada variable tiene su propia copia. Los tipos por referencia guardan una direccion hacia un objeto compartido.</figcaption>
</figure>
</div>
</div>
<ul>
<li><strong>Tipos por valor</strong>: <code>int</code>, <code>double</code>, <code>bool</code>, <code>char</code> y los demás tipos numéricos. La variable guarda el dato directamente. Copiarla crea una copia independiente.</li>
<li><strong>Tipos por referencia</strong>: <code>string</code>, los arreglos (Semana 6) y las clases que definas desde la Unidad 3. La variable guarda una dirección hacia el dato real, que vive aparte. Copiar la variable copia la dirección, no el contenido: las dos variables terminan apuntando al mismo dato.</li>
</ul>
<p>Por ahora vas a trabajar sobre todo con tipos por valor y con <code>string</code>. La diferencia se vuelve crítica más adelante, cuando pases arreglos y objetos como parámetros de una función.</p>
</section>
<section id="tipos-numéricos-cuál-usar-y-cuándo" class="level3">
<h3 class="anchored" data-anchor-id="tipos-numéricos-cuál-usar-y-cuándo">Tipos numéricos: cuál usar y cuándo</h3>
<p>C# tiene varios tipos numéricos, cada uno con un tamaño y un propósito distinto.</p>
<div class="diagrama">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="imagenes/mapa-tipos-numericos.svg" class="img-fluid figure-img" alt="Mapa de los tipos numericos de C Sharp: sbyte, short, int y long segun su tamano en bits, y float, double y decimal segun su precision"></p>
<figcaption>Los tipos enteros se diferencian por su tamaño en bits y por eso por el rango de valores que admiten. Los tipos reales se diferencian por su precision.</figcaption>
</figure>
</div>
</div>
<p>Para este curso, la regla práctica es corta:</p>
<ul>
<li><strong>Cuenta cosas con <code>int</code>.</strong> Es el tipo entero por omisión y alcanza para prácticamente cualquier cantidad que vayas a manejar en los ejercicios del semestre.</li>
<li><strong>Mide cosas con <code>double</code>.</strong> Es el tipo real por omisión: precios, promedios, medidas.</li>
<li>Vas a conocer <code>decimal</code> en esta semana porque explica un comportamiento de <code>double</code> que necesitas entender antes de calcular con dinero, aunque en este curso sigas usando <code>double</code> para mantener la sintaxis simple.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dt">double</span> resultado <span class="op">=</span> <span class="fl">0.1</span> <span class="op">+</span> <span class="fl">0.2</span><span class="op">;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>resultado<span class="op">);</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="dt">decimal</span> resultadoExacto <span class="op">=</span> <span class="fl">0.1m</span> <span class="op">+</span> <span class="fl">0.2m</span><span class="op">;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>resultadoExacto<span class="op">);</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>0.30000000000000004
0.3</code></pre>
<p><code>double</code> no representa exactamente todas las fracciones decimales, porque internamente guarda el número en base binaria. Para la mayoría de los cálculos del curso esa diferencia no se nota. Cuando trabajes con dinero de verdad, fuera de este curso, ese es el motivo por el que se usa <code>decimal</code>.</p>
</section>
<section id="caracteres-texto-y-valores-lógicos" class="level3">
<h3 class="anchored" data-anchor-id="caracteres-texto-y-valores-lógicos">Caracteres, texto y valores lógicos</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Guarda</th>
<th>Ejemplo</th>
<th>Nota</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>char</code></td>
<td>Un solo carácter, entre comillas simples</td>
<td><code>char inicial = 'P';</code></td>
<td>Es un tipo por valor, aunque parezca texto</td>
</tr>
<tr class="even">
<td><code>string</code></td>
<td>Texto de cualquier longitud, entre comillas dobles</td>
<td><code>string nombre = "Cable HDMI";</code></td>
<td>Es un tipo por referencia</td>
</tr>
<tr class="odd">
<td><code>bool</code></td>
<td><code>true</code> o <code>false</code>, nada más</td>
<td><code>bool activo = true;</code></td>
<td>Resultado natural de una comparación</td>
</tr>
</tbody>
</table>
</section>
<section id="var-y-el-tipo-explícito" class="level3">
<h3 class="anchored" data-anchor-id="var-y-el-tipo-explícito"><code>var</code> y el tipo explícito</h3>
<p><code>var</code> le pide al compilador que <strong>infiera</strong> el tipo a partir del valor que asignas. El tipo queda igual de fijo que si lo hubieras escrito tú: <code>var</code> no crea una variable de tipo flexible.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="dt">var</span> cantidad <span class="op">=</span> <span class="dv">12</span><span class="op">;</span>        <span class="co">// el compilador fija el tipo en int</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="dt">var</span> precio <span class="op">=</span> <span class="fl">4599.90</span><span class="op">;</span>     <span class="co">// el compilador fija el tipo en double</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Este curso usa el tipo explícito (<code>int cantidad = 12;</code>) en el material, porque para quien empieza es más fácil verificar que declaró el tipo que quería. Usa <code>var</code> cuando el tipo ya es obvio por el lado derecho de la asignación; en cualquier otro caso, prefiere escribirlo.</p>
</section>
<section id="valores-por-defecto" class="level3">
<h3 class="anchored" data-anchor-id="valores-por-defecto">Valores por defecto</h3>
<p>Toda variable de tipo por valor tiene un valor por defecto si la inicializas con la palabra clave <code>default</code> en lugar de un literal:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> contador <span class="op">=</span> <span class="kw">default</span><span class="op">;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="dt">double</span> total <span class="op">=</span> <span class="kw">default</span><span class="op">;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> encontrado <span class="op">=</span> <span class="kw">default</span><span class="op">;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"contador: {contador}, total: {total}, encontrado: {encontrado}"</span><span class="op">);</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>contador: 0, total: 0, encontrado: False</code></pre>
<p>El compilador exige que toda variable local tenga un valor antes de leerla. <code>default</code> es útil cuando el valor inicial no importa porque lo vas a sobrescribir enseguida, por ejemplo antes de convertir un dato leído por consola, como haces en la sección siguiente.</p>
</section>
</section>
<section id="entrada-y-salida-por-consola" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="entrada-y-salida-por-consola"><span class="header-section-number">5</span> Entrada y salida por consola</h2>
<p>Ya usaste <code>Console.WriteLine</code>, <code>Console.Write</code> y <code>Console.ReadLine</code> en la Semana 1. Esta semana los usas con intención: para construir un pequeño registro de datos.</p>
<div class="diagrama">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="imagenes/flujo-entrada-salida-consola.svg" class="img-fluid figure-img" alt="Flujo de cuatro pasos: pedir el dato, leerlo como texto, convertir el tipo y mostrar el resultado"></p>
<figcaption>Console.Write muestra el mensaje, Console.ReadLine devuelve siempre texto, una conversion cambia ese texto a un tipo numerico o logico, y Console.WriteLine muestra el resultado.</figcaption>
</figure>
</div>
</div>
<p>El punto que hay que fijar es este: <strong><code>Console.ReadLine</code> siempre devuelve <code>string</code></strong>, sin importar qué le pidas al usuario que escriba. Si necesitas un número, tienes que convertir ese texto tú mismo antes de poder operar con él.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Cantidad: "</span><span class="op">);</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span><span class="op">?</span> texto <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">();</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">// texto es "12", una cadena. Todavia no es un numero.</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">// int total = texto + 3;   // el compilador lo rechaza</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<section id="qué-significa-el-signo-de-interrogación-en-string" class="level3">
<h3 class="anchored" data-anchor-id="qué-significa-el-signo-de-interrogación-en-string">Qué significa el signo de interrogación en <code>string?</code></h3>
<p><code>Console.ReadLine</code> puede devolver <code>null</code> si la entrada estándar se cierra, por ejemplo cuando el programa corre sin una consola interactiva detrás. C# rastrea esa posibilidad con los <strong>tipos de referencia que admiten valores nulos</strong>: <code>string?</code> dice “esta variable puede contener un <code>string</code> o puede contener <code>null</code>”. Un <code>string</code> sin el <code>?</code> es una promesa al compilador de que la variable nunca va a ser <code>null</code>; si igual llega a serlo, el compilador te avisa con una advertencia.</p>
<p>Este curso usa <code>string?</code> en todo lo que venga directo de <code>Console.ReadLine</code>, y resuelve el posible <code>null</code> de una de estas dos formas:</p>
<ul>
<li><strong><code>??</code> (coalescencia nula).</strong> <code>Console.ReadLine() ?? ""</code> usa la cadena vacía si el resultado fue <code>null</code>.</li>
<li><strong><code>!</code> (perdón nulo, <em>null-forgiving</em>).</strong> <code>texto!</code> le dice al compilador “confía en mí, aquí no va a ser <code>null</code>”. No hace ninguna comprobación real: úsalo solo cuando estás seguro, porque si te equivocas el programa falla al ejecutarse en vez de avisarte al compilar.</li>
</ul>
</section>
</section>
<section id="conversión-de-tipos-convert-parse-y-tryparse" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="conversión-de-tipos-convert-parse-y-tryparse"><span class="header-section-number">6</span> Conversión de tipos: <code>Convert</code>, <code>Parse</code> y <code>TryParse</code></h2>
<p>C# ofrece varias formas de convertir un <code>string</code> a un tipo numérico. No son intercambiables: se diferencian en qué hacen cuando el texto no es un número válido.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Forma</th>
<th>Si el texto no es válido</th>
<th>Cuándo usarla</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Convert.ToInt32(texto)</code></td>
<td>Lanza una excepción (<code>FormatException</code>, o <code>ArgumentNullException</code> si el texto es <code>null</code>)</td>
<td>Casi nunca en este curso: mezcla mal el manejo de <code>null</code> con el de texto inválido</td>
</tr>
<tr class="even">
<td><code>int.Parse(texto)</code></td>
<td>Lanza <code>FormatException</code> y detiene el programa si no atrapas el error</td>
<td>Cuando ya validaste el texto por otro medio y confías en que es válido</td>
</tr>
<tr class="odd">
<td><code>int.TryParse(texto, out int valor)</code></td>
<td>Devuelve <code>false</code> y <code>valor</code> queda en <code>0</code>. No lanza ninguna excepción</td>
<td>La opción por omisión para leer datos del usuario</td>
</tr>
</tbody>
</table>
<p>Compruébalo con <code>Parse</code>, sin protegerlo:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Precio unitario: "</span><span class="op">);</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span><span class="op">?</span> texto <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">();</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="dt">double</span> precio <span class="op">=</span> <span class="dt">double</span><span class="op">.</span><span class="fu">Parse</span><span class="op">(</span>texto<span class="op">!);</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Precio registrado: {precio}"</span><span class="op">);</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Si el usuario escribe algo que no es un número, el programa se detiene con un error sin manejar:</p>
<pre class="text"><code>Precio unitario: abc
Unhandled exception. System.FormatException: The input string 'abc' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s)
   at Program.&lt;Main&gt;$(String[] args) in ...\Program.cs:line 18</code></pre>
<p><code>TryParse</code> evita ese desenlace. Intenta la conversión y te dice si funcionó con un valor lógico, en vez de interrumpir el programa:</p>
<div class="diagrama">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="imagenes/patron-tryparse.svg" class="img-fluid figure-img" alt="Diagrama de decision del patron TryParse: rama verdadera con el valor convertido y rama falsa sin excepcion"></p>
<figcaption>TryParse intenta la conversion y devuelve true o false. Si es true, la variable de salida queda con el valor convertido. Si es false, la variable queda en su valor por defecto y no se lanza ninguna excepcion.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Cantidad en inventario: "</span><span class="op">);</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span><span class="op">?</span> texto <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">();</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">if</span> <span class="op">(</span><span class="dt">int</span><span class="op">.</span><span class="fu">TryParse</span><span class="op">(</span>texto<span class="op">,</span> <span class="kw">out</span> <span class="dt">int</span> cantidad<span class="op">))</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Cantidad valida: {cantidad}"</span><span class="op">);</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="kw">else</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"'{texto}' no es un numero entero valido."</span><span class="op">);</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>out int cantidad</code> declara la variable de salida en el mismo lugar donde la usas. Dentro del bloque <code>if</code>, <code>cantidad</code> ya tiene el valor convertido y disponible.</p>
<p>Desde esta semana, <strong>usa <code>TryParse</code> para todo dato que venga del teclado</strong>. Vas a usar <code>Parse</code> y <code>Convert</code> en contadas ocasiones, cuando el dato venga de una fuente que ya validaste antes.</p>
</section>
<section id="caso-de-uso-el-primer-registro-del-sistema-de-gestión" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="caso-de-uso-el-primer-registro-del-sistema-de-gestión"><span class="header-section-number">7</span> Caso de uso: el primer registro del sistema de gestión</h2>
<p>El proyecto que vas a construir durante el semestre es un sistema de gestión: la semana 5 le suma decisiones y ciclos, la 10 arreglos y funciones, y la 16 lo reescribe con clases e interfaz gráfica. Esta semana sientas la base: representar los datos de <strong>un producto</strong> con las variables correctas y leerlos de forma segura por consola.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode csharp code-with-copy"><code class="sourceCode cs"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Herramientas de Programacion I - Semana 02</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">// Registro de un producto para el futuro sistema de gestion de inventario.</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"Sistema de gestion - Registro de producto"</span><span class="op">);</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"=========================================="</span><span class="op">);</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">();</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Nombre del producto: "</span><span class="op">);</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span> nombre <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">()</span> <span class="op">??</span> <span class="st">""</span><span class="op">;</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Precio unitario: "</span><span class="op">);</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span><span class="op">?</span> textoPrecio <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">();</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> precioValido <span class="op">=</span> <span class="dt">double</span><span class="op">.</span><span class="fu">TryParse</span><span class="op">(</span>textoPrecio<span class="op">,</span> <span class="kw">out</span> <span class="dt">double</span> precio<span class="op">);</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">Write</span><span class="op">(</span><span class="st">"Cantidad en inventario: "</span><span class="op">);</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="dt">string</span><span class="op">?</span> textoCantidad <span class="op">=</span> Console<span class="op">.</span><span class="fu">ReadLine</span><span class="op">();</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="dt">bool</span> cantidadValida <span class="op">=</span> <span class="dt">int</span><span class="op">.</span><span class="fu">TryParse</span><span class="op">(</span>textoCantidad<span class="op">,</span> <span class="kw">out</span> <span class="dt">int</span> cantidad<span class="op">);</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">();</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="kw">if</span> <span class="op">(!</span>precioValido <span class="op">||</span> <span class="op">!</span>cantidadValida<span class="op">)</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"No se pudo registrar el producto: revisa el precio y la cantidad."</span><span class="op">);</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="kw">else</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="op">{</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    <span class="dt">double</span> valorTotal <span class="op">=</span> precio <span class="op">*</span> cantidad<span class="op">;</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"Resumen del producto"</span><span class="op">);</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span><span class="st">"---------------------"</span><span class="op">);</span></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Nombre     : {nombre}"</span><span class="op">);</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Precio     : {precio}"</span><span class="op">);</span></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Cantidad   : {cantidad}"</span><span class="op">);</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    Console<span class="op">.</span><span class="fu">WriteLine</span><span class="op">(</span>$<span class="st">"Valor total: {valorTotal}"</span><span class="op">);</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Una corrida con datos válidos:</p>
<pre class="text"><code>Sistema de gestion - Registro de producto
==========================================

Nombre del producto: Cable HDMI 2 metros
Precio unitario: 4599.90
Cantidad en inventario: 12

Resumen del producto
---------------------
Nombre     : Cable HDMI 2 metros
Precio     : 4599.9
Cantidad   : 12
Valor total: 55198.799999999996</code></pre>
<p>Dos detalles reales de esta salida, no simplificados a propósito:</p>
<ul>
<li><code>Precio</code> imprime <code>4599.9</code>, sin el cero final que escribiste. <code>double</code> no guarda ceros decorativos: guarda el número.</li>
<li><code>Valor total</code> imprime <code>55198.799999999996</code> en vez de <code>55198.8</code>. Es la misma imprecisión de <code>double</code> que viste en la sección de tipos numéricos, ahora aplicada a un cálculo real. No es un error del programa: es el comportamiento documentado del tipo.</li>
</ul>
<p>Una corrida con un dato inválido, sin que el programa se caiga:</p>
<pre class="text"><code>Sistema de gestion - Registro de producto
==========================================

Nombre del producto: Mouse inalambrico
Precio unitario: abc
Cantidad en inventario: 5

No se pudo registrar el producto: revisa el precio y la cantidad.</code></pre>
<p><code>TryParse</code> dejó <code>precioValido</code> en <code>false</code> y el programa siguió corriendo hasta el final, sin lanzar ninguna excepción.</p>
</section>
<section id="errores-frecuentes" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">8</span> Errores frecuentes</h2>
<div class="error-caso">
<p><span class="etiqueta">Error 1</span></p>
<section id="formatexception-al-leer-un-número" class="level4">
<h4 class="anchored" data-anchor-id="formatexception-al-leer-un-número"><code>FormatException</code> al leer un número</h4>
<p><strong>Causa.</strong> Usaste <code>Parse</code> o <code>Convert.ToInt32</code> sobre un texto que no es un número válido, y nadie protegió esa conversión.</p>
<p><strong>Solución.</strong> Cambia a <code>TryParse</code> y decide qué hacer en la rama <code>false</code>, en vez de dejar que el programa se detenga con una excepción sin manejar.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 2</span></p>
<section id="el-compilador-rechaza-una-operación-entre-tipos" class="level4">
<h4 class="anchored" data-anchor-id="el-compilador-rechaza-una-operación-entre-tipos">El compilador rechaza una operación entre tipos</h4>
<p><strong>Causa.</strong> Intentaste sumar o comparar valores de tipos incompatibles, por ejemplo un <code>string</code> con un <code>int</code> sin convertir, o un <code>int</code> con un <code>bool</code>.</p>
<p><strong>Solución.</strong> Revisa el tipo de cada variable involucrada. El tipado fuerte de C# no permite las conversiones implícitas que sí acepta el pseudocódigo de Fundamentos de Programación.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 3</span></p>
<section id="el-texto-que-pide-el-dato-queda-pegado-a-la-respuesta" class="level4">
<h4 class="anchored" data-anchor-id="el-texto-que-pide-el-dato-queda-pegado-a-la-respuesta">El texto que pide el dato queda pegado a la respuesta</h4>
<p><strong>Causa.</strong> Usaste <code>Console.WriteLine</code> en vez de <code>Console.Write</code> para el mensaje que precede a un <code>Console.ReadLine</code>. <code>WriteLine</code> salta de línea antes de que el usuario escriba, y el mensaje queda separado de la respuesta.</p>
<p><strong>Solución.</strong> Usa <code>Console.Write</code> (sin <code>Line</code>) cuando el siguiente paso es leer una respuesta en la misma línea.</p>
</section>
</div>
</section>
<section id="lista-de-verificación-de-la-semana" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="lista-de-verificación-de-la-semana"><span class="header-section-number">9</span> Lista de verificación de la semana</h2>
<div class="checklist">
<ul class="task-list">
<li><label><input type="checkbox">Sabes qué genera el compilador a partir de las sentencias de nivel superior.</label></li>
<li><label><input type="checkbox">Distingues un tipo por valor de uno por referencia con un ejemplo propio.</label></li>
<li><label><input type="checkbox">Eliges <code>int</code> o <code>double</code> según el dato que vas a representar.</label></li>
<li><label><input type="checkbox">Sabes por qué <code>Console.ReadLine</code> siempre devuelve <code>string</code>.</label></li>
<li><label><input type="checkbox">Usas <code>TryParse</code> para convertir datos que vienen del teclado, sin que un dato inválido detenga el programa.</label></li>
<li><label><input type="checkbox">Explicas qué significa el <code>?</code> en <code>string?</code> y cuándo usar <code>!</code> para descartar un posible <code>null</code>.</label></li>
</ul>
</div>
</section>
<section id="trabajo-independiente" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="trabajo-independiente"><span class="header-section-number">10</span> Trabajo independiente</h2>
<p>Amplía el ejercicio de registro de producto:</p>
<ol type="1">
<li>Agrega una cuarta variable, <code>codigo</code>, de tipo <code>string</code>, y pide su valor por consola.</li>
<li>Agrega una quinta variable, <code>stockMinimo</code>, de tipo <code>int</code>, leída con <code>TryParse</code>.</li>
<li>En el resumen final, agrega una línea que indique si <code>cantidad</code> es menor que <code>stockMinimo</code>, usando lo que ya sabes de tipos lógicos (todavía sin <code>if</code>: basta con guardar el resultado de la comparación en una variable <code>bool</code> e imprimirla).</li>
<li>Prueba el programa dos veces: una con todos los datos válidos y otra con al menos un dato inválido, y confirma que el segundo caso no lanza ninguna excepción.</li>
</ol>
<p>Guarda el ejercicio en un proyecto nuevo, dentro de la misma carpeta de trabajos donde tienes <code>HolaPascual</code>. No hace falta subirlo a GitHub esta semana; retomas ese flujo cuando el proyecto del curso lo requiera.</p>
</section>
<section id="recursos" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="recursos"><span class="header-section-number">11</span> Recursos</h2>
<ul>
<li>Sentencias de nivel superior: <a href="https://learn.microsoft.com/es-es/dotnet/csharp/fundamentals/program-structure/top-level-statements">learn.microsoft.com/dotnet/csharp/fundamentals/program-structure/top-level-statements</a></li>
<li>El sistema de tipos de C#: <a href="https://learn.microsoft.com/es-es/dotnet/csharp/fundamentals/types/">learn.microsoft.com/dotnet/csharp/fundamentals/types</a></li>
<li>Tipos enteros integrados: <a href="https://learn.microsoft.com/es-es/dotnet/csharp/language-reference/builtin-types/integral-numeric-types">learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/integral-numeric-types</a></li>
<li>Tipos reales integrados: <a href="https://learn.microsoft.com/es-es/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types">learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types</a></li>
<li>Conversión de texto a número: <a href="https://learn.microsoft.com/es-es/dotnet/standard/base-types/parsing-numeric">learn.microsoft.com/dotnet/standard/base-types/parsing-numeric</a></li>
</ul>
<div class="pie-doc">
<p>Herramientas de Programación I (ET0047). Institución Universitaria Pascual Bravo. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Opus 5 de Anthropic. Todo el contenido fue revisado y validado. Las salidas de terminal son reales, obtenidas ejecutando el código exacto de esta guía contra el SDK de .NET 10.0.302.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-pascual-b-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
<p>Institución Universitaria Pascual Bravo. Facultad de Ingeniería</p>
</div>
    <div class="nav-footer-right">
<p>Semestre 2026-02</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>