<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Semana 1. Presentación del módulo y entorno de trabajo – Clases Pascual Bravo 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-63bd06c2c145d35a53f198c60a9c2611.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Unidad 1. Análisis descriptivo y exploratorio</a></li><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Semana 1. Presentación y entorno de trabajo</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Clases Pascual Bravo 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del módulo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Análisis descriptivo y exploratorio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-01/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Semana 1. Presentación y entorno de trabajo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../estadistica-para-analitica/semana-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semana 2. Tipos de variables</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#de-qué-va-esta-semana" id="toc-de-qué-va-esta-semana" class="nav-link active" data-scroll-target="#de-qué-va-esta-semana"><span class="header-section-number">1</span> De qué va esta semana</a></li>
  <li><a href="#la-estadística-como-proceso-de-decisión" id="toc-la-estadística-como-proceso-de-decisión" class="nav-link" data-scroll-target="#la-estadística-como-proceso-de-decisión"><span class="header-section-number">2</span> La estadística como proceso de decisión</a></li>
  <li><a href="#el-mapa-del-módulo" id="toc-el-mapa-del-módulo" class="nav-link" data-scroll-target="#el-mapa-del-módulo"><span class="header-section-number">3</span> El mapa del módulo</a>
  <ul class="collapse">
  <li><a href="#qué-hará-cada-unidad" id="toc-qué-hará-cada-unidad" class="nav-link" data-scroll-target="#qué-hará-cada-unidad">Qué hará cada unidad</a></li>
  </ul></li>
  <li><a href="#el-entorno-de-trabajo" id="toc-el-entorno-de-trabajo" class="nav-link" data-scroll-target="#el-entorno-de-trabajo"><span class="header-section-number">4</span> El entorno de trabajo</a>
  <ul class="collapse">
  <li><a href="#por-qué-un-entorno-virtual" id="toc-por-qué-un-entorno-virtual" class="nav-link" data-scroll-target="#por-qué-un-entorno-virtual">Por qué un entorno virtual</a></li>
  <li><a href="#versiones-de-referencia" id="toc-versiones-de-referencia" class="nav-link" data-scroll-target="#versiones-de-referencia">Versiones de referencia</a></li>
  </ul></li>
  <li><a href="#instalación-paso-a-paso" id="toc-instalación-paso-a-paso" class="nav-link" data-scroll-target="#instalación-paso-a-paso"><span class="header-section-number">5</span> Instalación paso a paso</a>
  <ul class="collapse">
  <li><a href="#python" id="toc-python" class="nav-link" data-scroll-target="#python"><span class="paso">1</span> Python</a></li>
  <li><a href="#la-carpeta-del-módulo-y-el-entorno-virtual" id="toc-la-carpeta-del-módulo-y-el-entorno-virtual" class="nav-link" data-scroll-target="#la-carpeta-del-módulo-y-el-entorno-virtual"><span class="paso">2</span> La carpeta del módulo y el entorno virtual</a></li>
  <li><a href="#las-librerías" id="toc-las-librerías" class="nav-link" data-scroll-target="#las-librerías"><span class="paso">3</span> Las librerías</a></li>
  </ul></li>
  <li><a href="#verificación" id="toc-verificación" class="nav-link" data-scroll-target="#verificación"><span class="header-section-number">6</span> Verificación</a></li>
  <li><a href="#demostración-por-qué-se-mide-más-de-una-vez" id="toc-demostración-por-qué-se-mide-más-de-una-vez" class="nav-link" data-scroll-target="#demostración-por-qué-se-mide-más-de-una-vez"><span class="header-section-number">7</span> Demostración: por qué se mide más de una vez</a>
  <ul class="collapse">
  <li><a href="#qué-acaba-de-pasar" id="toc-qué-acaba-de-pasar" class="nav-link" data-scroll-target="#qué-acaba-de-pasar">Qué acaba de pasar</a></li>
  </ul></li>
  <li><a href="#los-tres-formatos-de-almacenamiento" id="toc-los-tres-formatos-de-almacenamiento" class="nav-link" data-scroll-target="#los-tres-formatos-de-almacenamiento"><span class="header-section-number">8</span> Los tres formatos de almacenamiento</a>
  <ul class="collapse">
  <li><a href="#anatomía-de-una-tabla-de-datos" id="toc-anatomía-de-una-tabla-de-datos" class="nav-link" data-scroll-target="#anatomía-de-una-tabla-de-datos">Anatomía de una tabla de datos</a></li>
  </ul></li>
  <li><a href="#trabajo-independiente-de-la-semana" id="toc-trabajo-independiente-de-la-semana" class="nav-link" data-scroll-target="#trabajo-independiente-de-la-semana"><span class="header-section-number">9</span> Trabajo independiente de la semana</a></li>
  <li><a href="#lo-que-viene" id="toc-lo-que-viene" class="nav-link" data-scroll-target="#lo-que-viene"><span class="header-section-number">10</span> Lo que viene</a></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">11</span> Errores frecuentes</a></li>
  <li><a href="#lista-de-chequeo-del-entorno" id="toc-lista-de-chequeo-del-entorno" class="nav-link" data-scroll-target="#lista-de-chequeo-del-entorno"><span class="header-section-number">12</span> Lista de chequeo del entorno</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">13</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Unidad 1. Análisis descriptivo y exploratorio</a></li><li class="breadcrumb-item"><a href="../../estadistica-para-analitica/semana-01/index.html">Semana 1. Presentación y entorno de trabajo</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Semana 1. Presentación del módulo y entorno de trabajo</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">12 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<tbody>
<tr class="odd">
<td>Módulo</td>
<td>Estadística para Analítica</td>
</tr>
<tr class="even">
<td>Programa</td>
<td>Especialización en Big Data</td>
</tr>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Análisis descriptivo y exploratorio de datos</td>
</tr>
</tbody>
</table>
</div>
<p><a href="presentacion-introduccion.html" class="btn btn-primary" role="button">Abrir la presentación de la sesión</a></p>
<section id="de-qué-va-esta-semana" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="de-qué-va-esta-semana"><span class="header-section-number">1</span> De qué va esta semana</h2>
<p>Esta semana no tiene entregable ni nota. Hace tres cosas: te muestra cómo está armado el módulo, deja el entorno de Python instalado y verificado, y pone sobre la mesa el problema que la estadística existe para resolver.</p>
<p>Al cerrar la guía deberías poder:</p>
<ol type="1">
<li>Ubicar cada unidad del módulo dentro del ciclo de resolución de un problema con datos.</li>
<li>Ejecutar Python en un entorno virtual con las siete librerías del semestre.</li>
<li>Decir qué aporta cada librería y por qué están todas.</li>
<li>Explicar por qué una medición repetida no devuelve el mismo número, y qué consecuencia tiene eso para una decisión.</li>
</ol>
</section>
<section id="la-estadística-como-proceso-de-decisión" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="la-estadística-como-proceso-de-decisión"><span class="header-section-number">2</span> La estadística como proceso de decisión</h2>
<p>Resolver un problema con datos toma cuatro pasos:</p>
<ul>
<li><strong>Formular la pregunta.</strong> Qué se quiere saber, sobre qué proceso, y en qué términos medibles se deja plantear.</li>
<li><strong>Recoger los datos.</strong> Qué se mide, cada cuánto, con qué instrumento y quién responde por el registro.</li>
<li><strong>Analizar.</strong> Con el método que admite la naturaleza de esas variables.</li>
<li><strong>Interpretar y decidir.</strong> Qué se hace con el resultado y con cuánta confianza.</li>
</ul>
<div class="diagrama">
<p><img src="imagenes/ciclo-estadistico.svg" class="img-fluid" alt="Los cuatro pasos en secuencia: formular la pregunta, recoger los datos, analizar con el método que corresponde e interpretar y decidir, con una flecha de retorno desde la decisión hasta la pregunta."></p>
</div>
<p>Los cuatro pasos pesan igual sobre el resultado. Un análisis impecable montado sobre datos mal recogidos produce una decisión equivocada con apariencia de rigor, y esa decisión hay que defenderla después ante quien la firma.</p>
<p>Toma el caso que atraviesa el módulo: un área de mantenimiento decide cuándo intervenir una máquina. Antes de que exista una tabla, alguien fijó qué variable representa el desgaste, cada cuánto se lee el instrumento y quién responde por el registro. Cambia una de esas decisiones y cambia la conclusión.</p>
<p>El módulo recorre los cuatro pasos y le da al diseño de la medición el mismo peso que al cálculo.</p>
</section>
<section id="el-mapa-del-módulo" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-mapa-del-módulo"><span class="header-section-number">3</span> El mapa del módulo</h2>
<p>Dieciséis semanas repartidas en tres unidades. Cada una responde una pregunta distinta sobre el mismo caso.</p>
<div class="diagrama">
<p><img src="imagenes/mapa-modulo.svg" class="img-fluid" alt="Las tres unidades en secuencia: la 1 entre las semanas 1 y 5 para describir, la 2 entre la 6 y la 10 para modelar la incertidumbre, y la 3 entre la 11 y la 16 para inferir sobre la población."></p>
</div>
<div data-tbl-colwidths="[10,30,48,12]">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 30%">
<col style="width: 48%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Unidad</th>
<th>La pregunta que responde</th>
<th>Lo que produce</th>
<th style="text-align: center;">Cierre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Qué hay en estos datos</td>
<td>Un informe exploratorio con gráficos y resúmenes numéricos</td>
<td style="text-align: center;">30%</td>
</tr>
<tr class="even">
<td>2</td>
<td>Qué tan probable es lo que observo</td>
<td>Un modelo de probabilidad ajustado al fenómeno</td>
<td style="text-align: center;">30%</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Qué puedo afirmar sobre lo que no medí</td>
<td>Conclusiones sobre la población, con su margen de error declarado</td>
<td style="text-align: center;">40%</td>
</tr>
</tbody>
</table>
</div>
<section id="qué-hará-cada-unidad" class="level3">
<h3 class="anchored" data-anchor-id="qué-hará-cada-unidad">Qué hará cada unidad</h3>
<p><strong>Unidad 1. Describir lo que hay.</strong> Construirás tablas de frecuencia, histogramas, medidas de localización y dispersión, boxplots y gráficos de dispersión. El cierre será un informe exploratorio que muestre qué dicen los datos observados.</p>
<div class="diagrama">
<p><img src="imagenes/caso-unidad-1.svg" class="img-fluid" alt="Diagrama de cajas de la duración de intervenciones preventivas, predictivas y correctivas, con sus observaciones superpuestas y medianas diferenciadas."></p>
</div>
<p><strong>Unidad 2. Modelar la incertidumbre.</strong> Ajustarás distribuciones de probabilidad y las usarás para calcular la posibilidad de eventos que todavía no ocurrieron. El cierre será un modelo que responda preguntas sobre el fenómeno.</p>
<div class="diagrama">
<p><img src="imagenes/caso-unidad-2.svg" class="img-fluid" alt="Histograma de la duración de las intervenciones correctivas con una distribución ajustada y el área correspondiente a duraciones superiores a 240 minutos."></p>
</div>
<p><strong>Unidad 3. Inferir sobre el proceso.</strong> Construirás intervalos de confianza, pruebas de hipótesis, comparaciones y modelos de regresión. El cierre presentará conclusiones sobre el proceso y declarará el margen de error.</p>
<div class="diagrama">
<p><img src="imagenes/caso-unidad-3.svg" class="img-fluid" alt="Relación entre horas de operación y duración de las intervenciones, con rectas de regresión y bandas de confianza para intervenciones preventivas y correctivas."></p>
</div>
<p>Las tres unidades trabajan sobre un mismo caso. Lo primero es <strong>definir el proceso</strong>: qué se observa, qué variables lo describen y cómo se registra. Sobre esa definición se monta después el modelo y, al final, la inferencia. El alcance del caso se acuerda en la Semana 02.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>El método del módulo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cada tema pasa por tres momentos:</p>
<ol type="1">
<li><strong>Concepto.</strong> Precisamos qué afirma el resultado y bajo qué supuestos se sostiene.</li>
<li><strong>Implementación.</strong> Escribimos el procedimiento en Python y lo ejecutamos sobre datos.</li>
<li><strong>Simulación.</strong> Repetimos el procedimiento muchas veces y contrastamos su comportamiento con lo que predice la teoría.</li>
</ol>
<p>Ese contraste construye criterio. Ves de dónde sale una distribución muestral y mides cada cuánto falla en la práctica un intervalo de confianza.</p>
</div>
</div>
</section>
</section>
<section id="el-entorno-de-trabajo" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="el-entorno-de-trabajo"><span class="header-section-number">4</span> El entorno de trabajo</h2>
<p>Todo el módulo se programa en Python. Un análisis que llega sin el código que lo produjo no se puede reproducir ni auditar, y la estadística que no se ejecuta se olvida.</p>
<p>Estas son las piezas y lo que hace cada una.</p>
<div class="diagrama">
<p><img src="imagenes/flujo-librerias.svg" class="img-fluid" alt="Los archivos .csv, .txt y .xlsx entran con pandas a un DataFrame. De ahí salen dos caminos: gráficos con matplotlib y seaborn, y cálculo, modelos y pruebas con numpy, scipy y statsmodels. Los dos desembocan en el informe con la decisión."></p>
</div>
<div data-tbl-colwidths="[18,82]">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th>Librería</th>
<th>Qué aporta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>pandas</td>
<td>Carga los datos y los deja como tabla con columnas con nombre</td>
</tr>
<tr class="even">
<td>numpy</td>
<td>Cálculo numérico y generación de números aleatorios para simular</td>
</tr>
<tr class="odd">
<td>openpyxl</td>
<td>Es la que permite a pandas leer y escribir <code>.xlsx</code></td>
</tr>
<tr class="even">
<td>matplotlib</td>
<td>Motor de los gráficos</td>
</tr>
<tr class="odd">
<td>seaborn</td>
<td>Gráficos estadísticos sobre matplotlib, con menos código</td>
</tr>
<tr class="even">
<td>scipy</td>
<td>Distribuciones de probabilidad y pruebas de hipótesis</td>
</tr>
<tr class="odd">
<td>statsmodels</td>
<td>Modelos de regresión y ANOVA con la salida que se reporta</td>
</tr>
</tbody>
</table>
</div>
<section id="por-qué-un-entorno-virtual" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-un-entorno-virtual">Por qué un entorno virtual</h3>
<p>Un entorno virtual es una carpeta con una copia aislada de Python y sus librerías. Lo que instalas adentro no toca el Python del sistema ni el de otros proyectos.</p>
<div class="diagrama">
<p><img src="imagenes/entorno-virtual.svg" class="img-fluid" alt="El Python del sistema, del que dependen otros programas, y a su derecha el entorno .venv, un contenedor aparte que encierra una copia aislada de Python y las siete librerías con su versión fijada."></p>
</div>
<p>Sirve para dos cosas concretas. La primera, que actualizar una librería para otro proyecto no rompa el código de este. La segunda, que fijar las versiones haga que el mismo script produzca el mismo resultado en tu máquina, en la mía y en la de quien revise tu informe dentro de un año.</p>
</section>
<section id="versiones-de-referencia" class="level3">
<h3 class="anchored" data-anchor-id="versiones-de-referencia">Versiones de referencia</h3>
<p>Esta guía se probó con estas versiones. Recrea el entorno con las versiones exactas de la tabla; el <code>requirements.txt</code> del paso 3 las fija con <code>==</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Herramienta</th>
<th>Versión probada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Python</td>
<td>3.13.4</td>
</tr>
<tr class="even">
<td>pandas</td>
<td>2.3.1</td>
</tr>
<tr class="odd">
<td>numpy</td>
<td>2.3.2</td>
</tr>
<tr class="even">
<td>scipy</td>
<td>1.17.0</td>
</tr>
<tr class="odd">
<td>matplotlib</td>
<td>3.10.8</td>
</tr>
<tr class="even">
<td>seaborn</td>
<td>0.13.2</td>
</tr>
<tr class="odd">
<td>statsmodels</td>
<td>0.14.6</td>
</tr>
<tr class="even">
<td>openpyxl</td>
<td>3.1.5</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="instalación-paso-a-paso" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="instalación-paso-a-paso"><span class="header-section-number">5</span> Instalación paso a paso</h2>
<section id="python" class="level3">
<h3 class="anchored" data-anchor-id="python"><span class="paso">1</span> Python</h3>
<p>Descarga la versión <strong>3.13</strong> desde <a href="https://www.python.org/downloads/">python.org/downloads</a>.</p>
<p>En Windows, <strong>marca la casilla <code>Add python.exe to PATH</code></strong> en la primera pantalla del instalador. Es fácil pasarla por alto, y sin ella el comando <code>python</code> no funciona en la terminal.</p>
<p>En macOS y Linux el sistema ya trae Python, pero suele ser una versión vieja que además usa el sistema operativo. Comprueba con <code>python3 --version</code> y, si es anterior a 3.11, instala la 3.13 aparte.</p>
</section>
<section id="la-carpeta-del-módulo-y-el-entorno-virtual" class="level3">
<h3 class="anchored" data-anchor-id="la-carpeta-del-módulo-y-el-entorno-virtual"><span class="paso">2</span> La carpeta del módulo y el entorno virtual</h3>
<p>Crea una carpeta para todo el semestre y ubícate en ella:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> estadistica-analitica</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> estadistica-analitica</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Crea el entorno virtual dentro de esa carpeta:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-m</span> venv .venv</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Actívalo. El comando cambia según el sistema:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Windows, PowerShell</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="ex">.venv\Scripts\Activate.ps1</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Windows, Git Bash</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/Scripts/activate</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># macOS y Linux</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Cuando queda activo, el nombre <code>(.venv)</code> aparece al comienzo de la línea de la terminal. Si no lo ves, no está activo, y todo lo que instales va a parar a otro lado.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>El entorno se activa en cada terminal nueva
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cerrar la terminal desactiva el entorno. Al día siguiente, cuando vuelvas a la carpeta, tienes que activarlo otra vez antes de trabajar. Es el tropiezo más común de las primeras semanas.</p>
</div>
</div>
</section>
<section id="las-librerías" class="level3">
<h3 class="anchored" data-anchor-id="las-librerías"><span class="paso">3</span> Las librerías</h3>
<p>Con el entorno activo, crea un archivo <code>requirements.txt</code> con este contenido:</p>
<pre class="text"><code>pandas==2.3.1
numpy==2.3.2
scipy==1.17.0
matplotlib==3.10.8
seaborn==0.13.2
statsmodels==0.14.6
openpyxl==3.1.5</code></pre>
<p>E instálalas de una vez:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Fijar las versiones con <code>==</code> es lo que hace reproducible el análisis. El archivo se versiona junto con el código: quien reciba tu informe puede recrear el entorno exacto con una sola orden.</p>
</section>
</section>
<section id="verificación" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="verificación"><span class="header-section-number">6</span> Verificación</h2>
<p>Con el entorno activo, ejecuta:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-c</span> <span class="st">"import pandas, numpy, scipy, matplotlib, seaborn, statsmodels; print('todo listo')"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Si imprime <code>todo listo</code>, ya está. Cualquier otra cosa significa que falta una librería o que el entorno no está activo.</p>
<p>Para ver las versiones instaladas:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-c</span> <span class="st">"import pandas, numpy, scipy; print(pandas.__version__, numpy.__version__, scipy.__version__)"</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>2.3.1 2.3.2 1.17.0</code></pre>
</section>
<section id="demostración-por-qué-se-mide-más-de-una-vez" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="demostración-por-qué-se-mide-más-de-una-vez"><span class="header-section-number">7</span> Demostración: por qué se mide más de una vez</h2>
<p>Esta es la demostración principal de la semana y no hay que entregar nada con ella. La corremos en la sesión y la repites en tu equipo para comprobar que el entorno funciona.</p>
<p>Vamos a medir algo real: cuánto tarda tu computador en ordenar una lista de cien mil números. La operación es idéntica en cada repetición, el tamaño no cambia y la máquina es la misma.</p>
<p>Crea un archivo <code>experimento.py</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">2026</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>filas <span class="op">=</span> []</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">201</span>):</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    datos <span class="op">=</span> [random.random() <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">100_000</span>)]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    inicio <span class="op">=</span> time.perf_counter()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    datos.sort()</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    fin <span class="op">=</span> time.perf_counter()</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    filas.append({</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"medicion"</span>: i,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"tiempo_ms"</span>: <span class="bu">round</span>((fin <span class="op">-</span> inicio) <span class="op">*</span> <span class="dv">1000</span>, <span class="dv">3</span>),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"tamano"</span>: <span class="dv">100_000</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>mediciones <span class="op">=</span> pd.DataFrame(filas)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>mediciones.to_csv(<span class="st">"tiempos_ordenamiento.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mediciones.head())</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mediciones[<span class="st">"tiempo_ms"</span>].describe())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ejecútalo con <code>python experimento.py</code>. Tarda alrededor de un minuto.</p>
<p>Esta es la salida en la máquina donde preparé la guía:</p>
<pre class="text"><code>   medicion  tiempo_ms  tamano
0         1     23.650  100000
1         2     22.488  100000
2         3     25.532  100000
3         4     25.649  100000
4         5     25.361  100000

count    200.000000
mean      22.645985
std        4.305880
min       15.767000
25%       18.478000
50%       23.849500
75%       25.551000
max       38.598000
Name: tiempo_ms, dtype: float64</code></pre>
<section id="qué-acaba-de-pasar" class="level3">
<h3 class="anchored" data-anchor-id="qué-acaba-de-pasar">Qué acaba de pasar</h3>
<p>Doscientas repeticiones de la misma operación, y ni una sola coincide con otra. La más rápida tardó 15.8 milisegundos y la más lenta 38.6: <strong>la más lenta se demoró más del doble que la más rápida</strong>.</p>
<p>Tus números van a ser distintos a estos, y eso también es parte del punto.</p>
<p>La causa no es el azar puro. El sistema operativo reparte el procesador entre muchos procesos, la memoria caché a veces tiene los datos a la mano y a veces no, y otros programas compiten por el equipo. Ninguno de esos factores se puede controlar por completo desde el programa.</p>
<p>Fíjate en el <code>random.seed(2026)</code> de la tercera línea. Fija la secuencia de números aleatorios que se generan, así que la <strong>lista que se ordena es siempre la misma</strong>. Aun controlando eso, los tiempos varían. La variabilidad no viene de los datos: viene de la medición.</p>
<p>De ahí sale la pregunta que ordena el módulo entero: si cada medición da distinto, <strong>¿cuál es el valor verdadero?</strong> Para responderla, separa cuatro ideas:</p>
<ul>
<li>La <strong>población</strong> es el conjunto completo de resultados que podría producir el proceso. En este experimento incluye todos los tiempos que obtendrías al repetir la operación bajo condiciones comparables.</li>
<li>La <strong>muestra</strong> contiene los resultados que sí observaste: las 200 mediciones.</li>
<li>Un <strong>parámetro</strong> resume una propiedad de la población, como su media. Permanece desconocido porque no puedes observar todos los resultados posibles.</li>
<li>Un <strong>estadístico</strong> es un número calculado con la muestra. La media de 22.6 milisegundos es un estadístico y funciona como estimación del parámetro.</li>
</ul>
<div class="diagrama">
<p><img src="imagenes/muestra-parametro.svg" class="img-fluid" alt="Del proceso completo, con su parámetro desconocido, sale por muestreo un conjunto de 200 mediciones. De esas mediciones se calcula una estimación, la media de 22.6 milisegundos. Una flecha punteada devuelve esa estimación al proceso como inferencia con margen de error."></p>
</div>
<p>Esa flecha punteada es la Unidad 3. Las unidades 1 y 2 construyen lo que hace falta para poder trazarla con honestidad: describir la muestra y modelar la variabilidad.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>La consecuencia práctica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un solo dato no es evidencia. Si alguien reporta que una máquina se demoró 38 minutos en una intervención, no sabes si es la máquina o es el ruido de una sola medición. Toda la discusión de este semestre nace ahí.</p>
</div>
</div>
</section>
</section>
<section id="los-tres-formatos-de-almacenamiento" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="los-tres-formatos-de-almacenamiento"><span class="header-section-number">8</span> Los tres formatos de almacenamiento</h2>
<p>El módulo organiza la información en tres formatos de almacenamiento. Cada uno tiene su lugar.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Formato</th>
<th>Qué es</th>
<th>Cuándo lo vas a usar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>.csv</code></td>
<td>Texto plano, valores separados por comas</td>
<td>El formato por omisión. Lo lee cualquier herramienta y ocupa poco</td>
</tr>
<tr class="even">
<td><code>.txt</code></td>
<td>Texto plano con otro separador, casi siempre tabulación</td>
<td>Lo que exportan muchos equipos de medición y sistemas industriales</td>
</tr>
<tr class="odd">
<td><code>.xlsx</code></td>
<td>Libro de Excel</td>
<td>Cuando el dato llega de un área que trabaja en Excel, o cuando el informe se entrega ahí</td>
</tr>
</tbody>
</table>
<p>Descarga el archivo de ejemplo, <a href="recursos/ordenes.csv"><code>ordenes.csv</code></a>, que tiene 12 órdenes de mantenimiento. Guárdalo en tu carpeta de trabajo.</p>
<p>Crea <code>formatos.py</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ordenes <span class="op">=</span> pd.read_csv(<span class="st">"ordenes.csv"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>ordenes.to_csv(<span class="st">"ordenes_copia.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ordenes.to_csv(<span class="st">"ordenes.txt"</span>, sep<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ordenes.to_excel(<span class="st">"ordenes.xlsx"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>desde_csv <span class="op">=</span> pd.read_csv(<span class="st">"ordenes_copia.csv"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>desde_txt <span class="op">=</span> pd.read_csv(<span class="st">"ordenes.txt"</span>, sep<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>desde_xlsx <span class="op">=</span> pd.read_excel(<span class="st">"ordenes.xlsx"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"csv  y txt :"</span>, desde_csv.equals(desde_txt))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"csv  y xlsx:"</span>, desde_csv.equals(desde_xlsx))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(desde_csv.head())</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(desde_csv.dtypes)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<pre class="text"><code>csv  y txt : True
csv  y xlsx: True

   orden maquina   turno        tipo criticidad  duracion_min  repuestos
0    101  TOR-01  manana  preventivo       baja         45.50          1
1    102  TOR-02   tarde  correctivo       alta        182.00          4
2    103  FRE-01   noche  preventivo      media         60.25          2
3    104  TOR-01  manana  predictivo       baja         30.00          0
4    105  FRE-02   tarde  correctivo       alta        210.50          5

orden             int64
maquina          object
turno            object
tipo             object
criticidad       object
duracion_min    float64
repuestos         int64
dtype: object</code></pre>
<p>Los tres archivos guardan exactamente lo mismo. El <code>index=False</code> evita que pandas agregue una columna extra con la numeración de las filas, que no es un dato y ensucia el archivo.</p>
<section id="anatomía-de-una-tabla-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="anatomía-de-una-tabla-de-datos">Anatomía de una tabla de datos</h3>
<p>Esa tabla tiene una estructura que se repite en todo el semestre:</p>
<div class="diagrama">
<p><img src="imagenes/anatomia-tabla.svg" class="img-fluid" alt="Tabla de órdenes de mantenimiento con la columna criticidad resaltada como variable, una fila resaltada como registro y la indicación de que cada fila representa una unidad de observación."></p>
</div>
<ul>
<li>La <strong>unidad de observación</strong> es lo que ocupa cada fila. Aquí, una orden de mantenimiento.</li>
<li>Cada <strong>variable</strong> es una columna: algo que se midió u observó de esa unidad.</li>
<li>Cada <strong>registro</strong> es una fila completa: todos los valores medidos de una misma unidad.</li>
</ul>
<p>Mira la última salida. Pandas leyó <code>duracion_min</code> como <code>float64</code> y <code>repuestos</code> como <code>int64</code>, y acertó en ambos. Pero puso <code>object</code> en <code>maquina</code>, <code>turno</code>, <code>tipo</code> y <code>criticidad</code>, que es como decir “texto y no sé nada más”. Ahí perdió información: <code>criticidad</code> tiene un orden natural, baja va antes que media y media antes que alta, y esa tabla no lo registra.</p>
<p>Quédate con la idea, porque la semana 2 arranca justo ahí: <strong>la naturaleza de una variable la declaras tú, no la adivina la herramienta</strong>, y de esa declaración depende qué análisis puedes hacer después.</p>
</section>
</section>
<section id="trabajo-independiente-de-la-semana" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="trabajo-independiente-de-la-semana"><span class="header-section-number">9</span> Trabajo independiente de la semana</h2>
<p>Reproduce en tu equipo la instalación, el experimento de las 200 mediciones y la conversión entre los tres formatos.</p>
<ul>
<li><strong>Entregable:</strong> ninguno. Esta semana no tiene peso evaluativo ni requiere subir archivos.</li>
<li><strong>Formato de trabajo:</strong> una carpeta local <code>estadistica-analitica</code> con <code>.venv</code>, <code>requirements.txt</code>, <code>experimento.py</code>, <code>formatos.py</code> y los archivos generados.</li>
<li><strong>Criterios de verificación:</strong> el entorno se activa, los imports funcionan, el experimento genera 200 registros y los archivos <code>.csv</code>, <code>.txt</code> y <code>.xlsx</code> conservan los mismos datos.</li>
</ul>
</section>
<section id="lo-que-viene" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="lo-que-viene"><span class="header-section-number">10</span> Lo que viene</h2>
<ul>
<li><strong>Semana 2.</strong> Clasificarás variables numéricas discretas y continuas, y variables categóricas nominales y ordinales.</li>
<li><strong>Semana 3.</strong> Construirás tablas de frecuencia e histogramas, y calcularás medidas de localización y dispersión.</li>
<li><strong>Semana 4.</strong> Interpretarás boxplots y cuantiles, y analizarás variables categóricas con gráficos de barras y tablas de contingencia.</li>
<li><strong>Semana 5.</strong> Examinarás relaciones con gráficos de dispersión y condicionales, y presentarás un informe exploratorio para cerrar la Unidad 1.</li>
</ul>
</section>
<section id="errores-frecuentes" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">11</span> Errores frecuentes</h2>
<div class="error-caso">
<p><span class="etiqueta">Error 1</span></p>
<section id="modulenotfounderror-no-module-named-pandas" class="level3">
<h3 class="anchored" data-anchor-id="modulenotfounderror-no-module-named-pandas">ModuleNotFoundError: No module named ‘pandas’</h3>
<p><strong>Causa.</strong> El entorno virtual no está activo, o instalaste las librerías sin activarlo.</p>
<p><strong>Solución.</strong> Mira el comienzo de la línea de la terminal. Si no dice <code>(.venv)</code>, actívalo con el comando de tu sistema y vuelve a intentar. Si ya está activo, ejecuta <code>pip install -r requirements.txt</code> otra vez: la primera vez fue a parar al Python del sistema.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 2</span></p>
<section id="modulenotfounderror-no-module-named-openpyxl-al-guardar-el-.xlsx" class="level3">
<h3 class="anchored" data-anchor-id="modulenotfounderror-no-module-named-openpyxl-al-guardar-el-.xlsx">ModuleNotFoundError: No module named ‘openpyxl’ al guardar el .xlsx</h3>
<p><strong>Causa.</strong> Pandas no escribe Excel por su cuenta: necesita openpyxl y lo importa solo cuando lo usas. Por eso el error aparece en la línea del <code>to_excel</code> y no al comienzo.</p>
<p><strong>Solución.</strong> <code>pip install openpyxl==3.1.5</code>, con el entorno activo.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 3</span></p>
<section id="filenotfounderror-ordenes.csv" class="level3">
<h3 class="anchored" data-anchor-id="filenotfounderror-ordenes.csv">FileNotFoundError: ordenes.csv</h3>
<p><strong>Causa.</strong> La terminal no está parada en la carpeta donde guardaste el archivo. Python busca los archivos desde el directorio actual, no desde donde está el script.</p>
<p><strong>Solución.</strong> Ejecuta <code>pwd</code> en macOS y Linux, o <code>cd</code> sin argumentos en PowerShell, para ver dónde estás. Muévete a la carpeta correcta con <code>cd</code> y vuelve a ejecutar.</p>
</section>
</div>
<div class="error-caso">
<p><span class="etiqueta">Error 4</span></p>
<section id="al-abrir-el-.csv-excel-mete-todo-en-una-sola-columna" class="level3">
<h3 class="anchored" data-anchor-id="al-abrir-el-.csv-excel-mete-todo-en-una-sola-columna">Al abrir el .csv, Excel mete todo en una sola columna</h3>
<p><strong>Causa.</strong> Excel en español espera punto y coma como separador, no coma.</p>
<p><strong>Solución.</strong> No abras el <code>.csv</code> con doble clic. Usa el <code>.xlsx</code> que generaste, que es justo para eso. Si necesitas el <code>.csv</code> en Excel, ábrelo desde <strong>Datos, Obtener datos, Desde un archivo de texto</strong> y elige la coma como separador.</p>
<p>No cambies el separador del archivo: la coma es el estándar y el resto del semestre asume que la tiene.</p>
</section>
</div>
</section>
<section id="lista-de-chequeo-del-entorno" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="lista-de-chequeo-del-entorno"><span class="header-section-number">12</span> Lista de chequeo del entorno</h2>
<div class="checklist">
<p><strong>Confirma que tienes todo esto antes de la próxima sesión</strong></p>
<ul class="task-list">
<li><label><input type="checkbox"><code>python --version</code> responde con 3.13 o superior</label></li>
<li><label><input type="checkbox">El entorno virtual se activa y muestra <code>(.venv)</code> en la terminal</label></li>
<li><label><input type="checkbox">El <code>import</code> de las seis librerías imprime <code>todo listo</code></label></li>
<li><label><input type="checkbox"><code>experimento.py</code> corrió y generó <code>tiempos_ordenamiento.csv</code> con 200 filas</label></li>
<li><label><input type="checkbox">Sabes explicar por qué las 200 mediciones dieron distinto</label></li>
<li><label><input type="checkbox">Ejecutaste <code>formatos.py</code> y los tres archivos coincidieron</label></li>
</ul>
</div>
</section>
<section id="recursos" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="recursos"><span class="header-section-number">13</span> Recursos</h2>
<ul>
<li>Descarga de Python: <a href="https://www.python.org/downloads/">python.org/downloads</a></li>
<li>Entornos virtuales: <a href="https://docs.python.org/es/3/library/venv.html">docs.python.org/es/3/library/venv.html</a></li>
<li>Lectura y escritura de datos con pandas: <a href="https://pandas.pydata.org/docs/user_guide/io.html">pandas.pydata.org/docs/user_guide/io.html</a></li>
<li>Dataset de ejemplo de esta guía: <a href="recursos/ordenes.csv"><code>ordenes.csv</code></a></li>
<li>James, G. et al.&nbsp;(2021). <em>An Introduction to Statistical Learning.</em> Capítulo 1.</li>
</ul>
<div class="pie-doc">
<p>Estadística para Analítica. Institución Universitaria Pascual Bravo. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Opus 5 de Anthropic. Todo el contenido fue revisado y validado. Las salidas de terminal son reales, producidas al ejecutar estos mismos programas durante la preparación del material.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-pascual-b-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
<p>Institución Universitaria Pascual Bravo. Facultad de Ingeniería</p>
</div>
    <div class="nav-footer-right">
<p>Semestre 2026-02</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>